#!/usr/bin/env python3
"""Run one ACT ELF on the selected-profile Flow Linux LiteDRAM SoC."""

import argparse
import hashlib
import os
import struct
import subprocess
import sys

from migen import ClockSignal, Instance, Module, ResetSignal
from litex.build.sim.config import SimConfig
from litex.soc.integration.builder import Builder
from litex.soc.integration.common import get_mem_data

SIM_DIR = os.path.dirname(os.path.abspath(__file__))
FLOW_ROOT = os.path.abspath(os.path.join(SIM_DIR, "..", ".."))
ACT_ROOT = os.path.join(FLOW_ROOT, "verification", "act4")
if SIM_DIR not in sys.path:
    sys.path.insert(0, SIM_DIR)

from linux_sim import (  # noqa: E402
    DDR_BASE, DDR_SIZE, LINUX_SYS_CLK_FREQUENCY_HZ, ROM_SIZE,
    elaborate, pack_ddr,
)
from multicore_sim import MTIME_FREQUENCY_HZ, MulticoreSimSoC  # noqa: E402

DEFAULT_TOOLCHAIN_ROOT = "/home/chen/opt/act4/gcc-2026.07.15"
DEFAULT_BOOTROM = os.path.join(ACT_ROOT, "platform", "build", "bootrom.bin")
MONITOR_SOURCE = os.path.join(SIM_DIR, "flow_act_completion_monitor.sv")


class ActCompletionMonitor(Module):
    def __init__(self, platform, cpu):
        platform.add_source(MONITOR_SOURCE)
        retire = cpu.retires[0]
        self.specials += Instance(
            "FlowActCompletionMonitor",
            p_NUM_HARTS=cpu.num_harts,
            i_clock=ClockSignal("sys"),
            i_reset=ResetSignal("sys"),
            i_retire_valid=retire.valid,
            i_retire_mem_en=retire.mem_en,
            i_retire_mem_is_write=retire.mem_is_write,
            i_retire_mem_addr=retire.mem_addr,
            i_retire_mem_aligned_addr=retire.mem_aligned_addr,
            i_retire_mem_wdata=retire.mem_wdata,
            i_retire_mem_wmask=retire.mem_wmask,
            i_hart_fatal=cpu.hart_fatal,
        )


def _sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _sim_structure_sha256(path):
    """Hash generated RTL while excluding LiteX's timestamp-only comments."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for line in handle:
            if line.startswith(b"// Date       : "):
                continue
            if line.startswith(b"//  Auto-Generated by LiteX on "):
                continue
            digest.update(line)
    return digest.hexdigest()


def _elf_entry(path):
    with open(path, "rb") as handle:
        header = handle.read(64)
    if header[:4] != b"\x7fELF" or header[4] != 2 or header[5] != 1:
        raise ValueError("ACT payload must be a little-endian ELF64 image")
    return struct.unpack_from("<Q", header, 24)[0]


def _find_symbol(elf_path, nm_executable, symbol):
    completed = subprocess.run(
        [nm_executable, "-n", elf_path], check=True, text=True,
        stdout=subprocess.PIPE)
    for line in completed.stdout.splitlines():
        fields = line.split()
        if len(fields) >= 3 and fields[-1] == symbol:
            return int(fields[0], 16)
    raise ValueError(f"ELF does not define required symbol {symbol}")


def _write_payload_binary(elf_path, output_dir, objcopy_executable):
    image_dir = os.path.join(output_dir, "act-images")
    os.makedirs(image_dir, exist_ok=True)
    output_path = os.path.join(image_dir, os.path.basename(elf_path) + ".bin")
    subprocess.run(
        [objcopy_executable, "-O", "binary", elf_path, output_path], check=True)
    size = os.path.getsize(output_path)
    if size <= 0 or size > DDR_SIZE:
        raise ValueError(f"ACT payload binary has invalid size: {size}")
    return output_path


def _write_sim_hash(gateware_dir):
    sim_path = os.path.join(gateware_dir, "sim.v")
    hash_path = os.path.join(gateware_dir, "act4-compiled-sim.sha256")
    digest = _sim_structure_sha256(sim_path)
    with open(hash_path, "w", encoding="utf-8") as handle:
        handle.write(digest + "\n")
    return digest


def _verify_sim_hash(gateware_dir):
    sim_path = os.path.join(gateware_dir, "sim.v")
    hash_path = os.path.join(gateware_dir, "act4-compiled-sim.sha256")
    if not os.path.isfile(hash_path):
        raise RuntimeError("compiled SoC hash is missing; rerun with --compile")
    with open(hash_path, encoding="utf-8") as handle:
        expected = handle.read().strip()
    actual = _sim_structure_sha256(sim_path)
    if actual != expected:
        raise RuntimeError(
            "generated SoC changed after compilation; rerun with --compile "
            f"(compiled={expected}, generated={actual})")
    return actual


def _check_debug_rtl(profile):
    marker = os.path.join(
        FLOW_ROOT, "design", "build", "rtl", "cluster", profile,
        "gshare", "linux", "cluster-profile.txt")
    values = {}
    with open(marker, encoding="utf-8") as handle:
        for line in handle:
            key, separator, value = line.strip().partition("=")
            if separator:
                values[key] = value
    expected_harts = {"single": 1, "dual": 2, "small": 4}[profile]
    if (values.get("profile") != profile or
            values.get("numHarts") != str(expected_harts) or
            values.get("corePreset") != "gshare" or
            values.get("privilegeProfile") != "linux" or
            values.get("rtlMode") != "debug" or values.get("tandem") != "true"):
        raise RuntimeError(
            f"ACT completion requires {profile}/gshare/linux debug RTL with tandem=true")


def main():
    parser = argparse.ArgumentParser(
        description="Run an ACT ELF on the selected-profile Linux LiteDRAM SoC.")
    parser.add_argument("--profile", choices=("single", "dual", "small"), default="small")
    parser.add_argument("--elf", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--bootrom", default=DEFAULT_BOOTROM)
    parser.add_argument("--max-cycles", type=int, default=2_000_000)
    parser.add_argument("--elaborate", action="store_true")
    parser.add_argument("--compile", action="store_true")
    parser.add_argument("--run", action="store_true")
    parser.add_argument("--jobs", type=int, default=min(20, os.cpu_count() or 1))
    parser.add_argument("--opt-level", choices=("O0", "O1", "O2", "O3"),
        default="O3")
    args = parser.parse_args()

    elf_path = os.path.abspath(args.elf)
    output_dir = os.path.abspath(args.output_dir)
    bootrom_path = os.path.abspath(args.bootrom)
    if not os.path.isfile(elf_path):
        parser.error(f"ACT ELF does not exist: {elf_path}")
    if not os.path.isfile(bootrom_path):
        parser.error(f"ACT boot ROM does not exist: {bootrom_path}")
    if args.max_cycles <= 0:
        parser.error("--max-cycles must be greater than zero")
    if args.jobs <= 0:
        parser.error("--jobs must be greater than zero")

    toolchain_root = os.environ.get("ACT4_TOOLCHAIN_ROOT", DEFAULT_TOOLCHAIN_ROOT)
    objcopy = os.path.join(toolchain_root, "bin", "riscv64-unknown-elf-objcopy")
    nm = os.path.join(toolchain_root, "bin", "riscv64-unknown-elf-nm")
    if not os.path.isfile(objcopy) or not os.path.isfile(nm):
        parser.error(f"ACT toolchain is incomplete: {toolchain_root}")

    entry = _elf_entry(elf_path)
    if entry != DDR_BASE:
        parser.error(
            f"ACT ELF entry must match Linux DDR base 0x{DDR_BASE:x}, got 0x{entry:x}")
    tohost = _find_symbol(elf_path, nm, "tohost")
    if not DDR_BASE <= tohost < DDR_BASE + DDR_SIZE:
        parser.error(f"tohost is outside Linux DDR: 0x{tohost:x}")

    if args.elaborate:
        elaborate(args.profile, "gshare", "debug")
    _check_debug_rtl(args.profile)

    payload_bin = _write_payload_binary(elf_path, output_dir, objcopy)
    ddr_init = pack_ddr([("act4", DDR_BASE, payload_bin)])
    rom_init = get_mem_data(
        bootrom_path, data_width=64, endianness="little", mem_size=ROM_SIZE)

    sim_config = SimConfig()
    sim_config.add_clocker("sys_clk", freq_hz=LINUX_SYS_CLK_FREQUENCY_HZ)
    sim_config.add_module("serial2console", "serial")
    soc = MulticoreSimSoC(
        sys_clk_freq=LINUX_SYS_CLK_FREQUENCY_HZ,
        rom_init=rom_init,
        cluster_profile=args.profile,
        core_preset="gshare",
        privilege_profile="linux",
        with_litedram=True,
        sdram_init=ddr_init)
    soc.submodules.act4_completion_monitor = ActCompletionMonitor(
        soc.platform, soc.cpu)

    print(
        "ACT4_LINUX_SOC "
        f"harts={soc.cpu.num_harts} entry=0x{entry:016x} "
        f"tohost=0x{tohost:016x} ram=0x{DDR_BASE:08x}+0x{DDR_SIZE:x} "
        f"timebase_hz={MTIME_FREQUENCY_HZ} elf_sha256={_sha256(elf_path)} "
        f"payload_sha256={_sha256(payload_bin)}",
        flush=True)

    builder = Builder(soc, output_dir=output_dir, compile_software=False)
    builder.build(
        run=False, sim_config=sim_config, trace=False,
        opt_level=args.opt_level, jobs=args.jobs, interactive=False)
    gateware_dir = os.path.join(output_dir, "gateware")

    if args.compile:
        subprocess.run(["bash", "build_sim.sh"], cwd=gateware_dir, check=True)
        compiled_hash = _write_sim_hash(gateware_dir)
        print(f"ACT4_SOC_COMPILED sim_sha256={compiled_hash}", flush=True)

    if args.run:
        sim_hash = _verify_sim_hash(gateware_dir)
        vsim = os.path.join(gateware_dir, "obj_dir", "Vsim")
        if not os.path.isfile(vsim):
            raise RuntimeError("compiled Vsim is missing; rerun with --compile")
        print(f"ACT4_SOC_RUN sim_sha256={sim_hash}", flush=True)
        completed = subprocess.run(
            [vsim, f"+act_tohost={tohost:016x}",
             f"+act_max_cycles={args.max_cycles}"],
            cwd=gateware_dir)
        return completed.returncode
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
