# KCU105 pins copied from the board-verified r3 generated constraints.
set_property LOC G10 [get_ports clk125_p]
set_property IOSTANDARD LVDS [get_ports clk125_p]
set_property LOC F10 [get_ports clk125_n]
set_property IOSTANDARD LVDS [get_ports clk125_n]

set_property LOC K22 [get_ports pcie_x8_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports pcie_x8_rst_n]
set_property LOC AB6 [get_ports pcie_x8_clk_p]
set_property LOC AB5 [get_ports pcie_x8_clk_n]

set_property LOC AB2 [get_ports {pcie_x8_rx_p[0]}]
set_property LOC AD2 [get_ports {pcie_x8_rx_p[1]}]
set_property LOC AF2 [get_ports {pcie_x8_rx_p[2]}]
set_property LOC AH2 [get_ports {pcie_x8_rx_p[3]}]
set_property LOC AJ4 [get_ports {pcie_x8_rx_p[4]}]
set_property LOC AK2 [get_ports {pcie_x8_rx_p[5]}]
set_property LOC AM2 [get_ports {pcie_x8_rx_p[6]}]
set_property LOC AP2 [get_ports {pcie_x8_rx_p[7]}]
set_property LOC AB1 [get_ports {pcie_x8_rx_n[0]}]
set_property LOC AD1 [get_ports {pcie_x8_rx_n[1]}]
set_property LOC AF1 [get_ports {pcie_x8_rx_n[2]}]
set_property LOC AH1 [get_ports {pcie_x8_rx_n[3]}]
set_property LOC AJ3 [get_ports {pcie_x8_rx_n[4]}]
set_property LOC AK1 [get_ports {pcie_x8_rx_n[5]}]
set_property LOC AM1 [get_ports {pcie_x8_rx_n[6]}]
set_property LOC AP1 [get_ports {pcie_x8_rx_n[7]}]

set_property LOC AC4 [get_ports {pcie_x8_tx_p[0]}]
set_property LOC AE4 [get_ports {pcie_x8_tx_p[1]}]
set_property LOC AG4 [get_ports {pcie_x8_tx_p[2]}]
set_property LOC AH6 [get_ports {pcie_x8_tx_p[3]}]
set_property LOC AK6 [get_ports {pcie_x8_tx_p[4]}]
set_property LOC AL4 [get_ports {pcie_x8_tx_p[5]}]
set_property LOC AM6 [get_ports {pcie_x8_tx_p[6]}]
set_property LOC AN4 [get_ports {pcie_x8_tx_p[7]}]
set_property LOC AC3 [get_ports {pcie_x8_tx_n[0]}]
set_property LOC AE3 [get_ports {pcie_x8_tx_n[1]}]
set_property LOC AG3 [get_ports {pcie_x8_tx_n[2]}]
set_property LOC AH5 [get_ports {pcie_x8_tx_n[3]}]
set_property LOC AK5 [get_ports {pcie_x8_tx_n[4]}]
set_property LOC AL3 [get_ports {pcie_x8_tx_n[5]}]
set_property LOC AM5 [get_ports {pcie_x8_tx_n[6]}]
set_property LOC AN3 [get_ports {pcie_x8_tx_n[7]}]

create_clock -name clk125_p -period 8.000 [get_ports clk125_p]
create_clock -name pcie_x8_clk_p -period 10.000 [get_ports pcie_x8_clk_p]
