// Generated by CIRCT firtool-1.128.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module BreezeBackend(
  input         clock,
                reset,
  input  [63:0] io_resetAddr,
  input         io_machineTimerInterrupt,
                io_machineSoftwareInterrupt,
  input  [63:0] io_time,
  input  [7:0]  io_externalInterrupts,
  input         io_supervisorExternalInterrupt,
  output        io_fetchBuffer_ready,
  input         io_fetchBuffer_valid,
  input  [63:0] io_fetchBuffer_bits_pc,
  input  [31:0] io_fetchBuffer_bits_inst,
                io_fetchBuffer_bits_rawInst,
  input  [2:0]  io_fetchBuffer_bits_instLen,
  input         io_fetchBuffer_bits_illegalCompressed,
                io_fetchBuffer_bits_instructionAccessFault,
                io_fetchBuffer_bits_instructionPageFault,
                io_fetchBuffer_bits_instructionFaultSecondParcel,
  input  [1:0]  io_fetchBuffer_bits_pred_predType,
  input         io_fetchBuffer_bits_pred_predTaken,
  input  [63:0] io_fetchBuffer_bits_pred_predPc,
  input  [7:0]  io_fetchBuffer_bits_pred_phtIdx,
  input         io_l1d_req_ready,
  output        io_l1d_req_valid,
  output [2:0]  io_l1d_req_bits_op,
  output [63:0] io_l1d_req_bits_vaddr,
  output [1:0]  io_l1d_req_bits_size,
  output        io_l1d_req_bits_signed,
  output [3:0]  io_l1d_req_bits_amoFunc,
  output        io_l1d_req_bits_aq,
                io_l1d_req_bits_rl,
  output [63:0] io_l1d_req_bits_wdata,
  output        io_l1d_req_bits_rd_isFp,
  output [4:0]  io_l1d_req_bits_rd_idx,
  output        io_l1d_req_bits_isFlw,
                io_l1d_s1Kill,
                io_l1d_s2Kill,
  input         io_l1d_resp_valid,
  input  [1:0]  io_l1d_resp_bits_kind,
  input  [63:0] io_l1d_resp_bits_data,
                io_l1d_resp_bits_excCause,
                io_l1d_resp_bits_tval,
  input         io_l1d_s2Hold,
  output        io_l1d_late_ready,
  input         io_l1d_late_valid,
                io_l1d_late_bits_rd_isFp,
  input  [4:0]  io_l1d_late_bits_rd_idx,
  input  [63:0] io_l1d_late_bits_data,
  input         io_l1d_late_bits_error,
                io_l1d_drained,
                io_l1d_mmioBusy,
  output        io_l1d_trapClearRsv,
  output [1:0]  io_l1d_csr_privilege,
  output        io_l1d_csr_mprv,
  output [1:0]  io_l1d_csr_mpp,
  output [7:0]  io_l1d_csr_pmpcfg_0,
                io_l1d_csr_pmpcfg_1,
                io_l1d_csr_pmpcfg_2,
                io_l1d_csr_pmpcfg_3,
                io_l1d_csr_pmpcfg_4,
                io_l1d_csr_pmpcfg_5,
                io_l1d_csr_pmpcfg_6,
                io_l1d_csr_pmpcfg_7,
  output [53:0] io_l1d_csr_pmpaddr_0,
                io_l1d_csr_pmpaddr_1,
                io_l1d_csr_pmpaddr_2,
                io_l1d_csr_pmpaddr_3,
                io_l1d_csr_pmpaddr_4,
                io_l1d_csr_pmpaddr_5,
                io_l1d_csr_pmpaddr_6,
                io_l1d_csr_pmpaddr_7,
  output        io_l1d_csr_permissionEvent,
  input         io_mmuIdle,
  output        io_translationBlocked,
                io_frontendBtbUpdate_valid,
  output [63:0] io_frontendBtbUpdate_pc,
                io_frontendBtbUpdate_target,
  output [1:0]  io_frontendBtbUpdate_predType,
  output        io_frontendPhtUpdate_valid,
  output [7:0]  io_frontendPhtUpdate_idx,
  output        io_frontendPhtUpdate_taken,
                io_frontendGhrUpdate_valid,
                io_frontendGhrUpdate_taken,
                io_frontendRedirect_valid,
                io_frontendRedirect_flush,
                io_frontendRedirect_cacheFlush,
  output [63:0] io_frontendRedirect_target,
                io_mmuContext_satp,
  output [1:0]  io_mmuContext_privilege,
  output        io_mmuContext_mprv,
  output [1:0]  io_mmuContext_mpp,
  output        io_mmuContext_sum,
                io_mmuContext_mxr,
  output [7:0]  io_mmuContext_pmpcfg_0,
                io_mmuContext_pmpcfg_1,
                io_mmuContext_pmpcfg_2,
                io_mmuContext_pmpcfg_3,
                io_mmuContext_pmpcfg_4,
                io_mmuContext_pmpcfg_5,
                io_mmuContext_pmpcfg_6,
                io_mmuContext_pmpcfg_7,
  output [53:0] io_mmuContext_pmpaddr_0,
                io_mmuContext_pmpaddr_1,
                io_mmuContext_pmpaddr_2,
                io_mmuContext_pmpaddr_3,
                io_mmuContext_pmpaddr_4,
                io_mmuContext_pmpaddr_5,
                io_mmuContext_pmpaddr_6,
                io_mmuContext_pmpaddr_7,
  output        io_sfence_valid,
  output [63:0] io_sfence_vaddr,
  output [15:0] io_sfence_asid,
  output        io_sfence_useVaddr,
                io_sfence_useAsid,
  input         io_hpmEvents_icacheAccess,
                io_hpmEvents_icacheMiss,
                io_hpmEvents_dcacheAccess,
                io_hpmEvents_dcacheMiss,
                io_hpmEvents_dcacheUncached,
  output        io_hartFatal,
                io_estop
);

  wire [63:0]      _jau_io_jmp_addr;
  wire             _bru_io_take_branch;
  wire [63:0]      _alu_io_alu_out;
  wire             _fpUnit_io_req_ready;
  wire             _fpUnit_io_result_valid;
  wire             _fpUnit_io_result_bits_rd_isFp;
  wire [4:0]       _fpUnit_io_result_bits_rd_idx;
  wire [63:0]      _fpUnit_io_result_bits_data;
  wire [4:0]       _fpUnit_io_result_bits_flags;
  wire             _fpUnit_io_committedFlagsOnly;
  wire             _divUnit_io_req_ready;
  wire             _divUnit_io_result_valid;
  wire [4:0]       _divUnit_io_result_bits_rd;
  wire [63:0]      _divUnit_io_result_bits_data;
  wire             _mulUnit_io_req_ready;
  wire             _mulUnit_io_result_valid;
  wire [4:0]       _mulUnit_io_result_bits_rd;
  wire [63:0]      _mulUnit_io_result_bits_data;
  wire             _writeback_io_div_ready;
  wire             _writeback_io_mul_ready;
  wire             _writeback_io_fp_ready;
  wire             _writeback_io_w2_valid;
  wire             _writeback_io_w2_bits_rd_isFp;
  wire [4:0]       _writeback_io_w2_bits_rd_idx;
  wire [63:0]      _writeback_io_w2_bits_data;
  wire             _writeback_io_gprWrite_valid;
  wire [4:0]       _writeback_io_gprWrite_bits_idx;
  wire [63:0]      _writeback_io_gprWrite_bits_data;
  wire             _writeback_io_fprWrite_valid;
  wire [4:0]       _writeback_io_fprWrite_bits_idx;
  wire [63:0]      _writeback_io_fprWrite_bits_data;
  wire             _writeback_io_clear_valid;
  wire             _writeback_io_clear_bits_isFp;
  wire [4:0]       _writeback_io_clear_bits_idx;
  wire             _writeback_io_fpFlags_valid;
  wire [4:0]       _writeback_io_fpFlags_bits;
  wire [1:0]       _writeback_io_conflict;
  wire             _writeback_io_idStarve;
  wire             _writeback_io_hartFatal;
  wire [31:0]      _scoreboard_io_gprBusy;
  wire [31:0]      _scoreboard_io_fprBusy;
  wire             _scoreboard_io_hazard;
  wire             _scoreboard_io_sourceStall_0;
  wire             _scoreboard_io_sourceStall_1;
  wire             _scoreboard_io_sourceStall_2;
  wire [63:0]      _csrFile_io_csr_old_data;
  wire [63:0]      _csrFile_io_csr_new_data;
  wire             _csrFile_io_csr_write_en;
  wire [2:0]       _csrFile_io_frm;
  wire             _csrFile_io_fp_enabled;
  wire [63:0]      _csrFile_io_trap_target;
  wire [63:0]      _csrFile_io_xret_target;
  wire [1:0]       _csrFile_io_current_privilege;
  wire             _csrFile_io_mret_illegal;
  wire             _csrFile_io_sret_illegal;
  wire             _csrFile_io_wfi_illegal;
  wire             _csrFile_io_sfence_vma_illegal;
  wire [1:0]       _csrFile_io_mmu_context_privilege;
  wire             _csrFile_io_mmu_context_mprv;
  wire [1:0]       _csrFile_io_mmu_context_mpp;
  wire [7:0]       _csrFile_io_mmu_context_pmpcfg_0;
  wire [7:0]       _csrFile_io_mmu_context_pmpcfg_1;
  wire [7:0]       _csrFile_io_mmu_context_pmpcfg_2;
  wire [7:0]       _csrFile_io_mmu_context_pmpcfg_3;
  wire [7:0]       _csrFile_io_mmu_context_pmpcfg_4;
  wire [7:0]       _csrFile_io_mmu_context_pmpcfg_5;
  wire [7:0]       _csrFile_io_mmu_context_pmpcfg_6;
  wire [7:0]       _csrFile_io_mmu_context_pmpcfg_7;
  wire [53:0]      _csrFile_io_mmu_context_pmpaddr_0;
  wire [53:0]      _csrFile_io_mmu_context_pmpaddr_1;
  wire [53:0]      _csrFile_io_mmu_context_pmpaddr_2;
  wire [53:0]      _csrFile_io_mmu_context_pmpaddr_3;
  wire [53:0]      _csrFile_io_mmu_context_pmpaddr_4;
  wire [53:0]      _csrFile_io_mmu_context_pmpaddr_5;
  wire [53:0]      _csrFile_io_mmu_context_pmpaddr_6;
  wire [53:0]      _csrFile_io_mmu_context_pmpaddr_7;
  wire             _csrFile_io_wfiWakeup;
  wire             _csrFile_io_interruptPending;
  wire [63:0]      _csrFile_io_interruptCause;
  wire             _csrFile_io_csr_illegal;
  wire [63:0]      _fpRegFile_io_rs1Data;
  wire [63:0]      _fpRegFile_io_rs2Data;
  wire [63:0]      _fpRegFile_io_rs3Data;
  wire [63:0]      _regFile_io_rs1_data;
  wire [63:0]      _regFile_io_rs2_data;
  wire [63:0]      _immGen_io_imm;
  wire             _fpDecoder_io_ctrl_valid;
  wire             _fpDecoder_io_ctrl_fpuValid;
  wire [1:0]       _fpDecoder_io_ctrl_localOp;
  wire             _fpDecoder_io_ctrl_isLoad;
  wire             _fpDecoder_io_ctrl_isStore;
  wire             _fpDecoder_io_ctrl_isDouble;
  wire             _fpDecoder_io_ctrl_writesFpr;
  wire             _fpDecoder_io_ctrl_writesGpr;
  wire             _fpDecoder_io_ctrl_usesFpr1;
  wire             _fpDecoder_io_ctrl_usesFpr2;
  wire             _fpDecoder_io_ctrl_usesFpr3;
  wire             _fpDecoder_io_ctrl_usesGpr1;
  wire [3:0]       _fpDecoder_io_ctrl_operation;
  wire             _fpDecoder_io_ctrl_opMod;
  wire [2:0]       _fpDecoder_io_ctrl_srcFmt;
  wire [2:0]       _fpDecoder_io_ctrl_dstFmt;
  wire [1:0]       _fpDecoder_io_ctrl_intFmt;
  wire [2:0]       _fpDecoder_io_ctrl_rm;
  wire             _fpDecoder_io_ctrl_usesArchitecturalRm;
  wire [3:0]       _decoder_io_exe_ctrl_alu_op;
  wire [2:0]       _decoder_io_exe_ctrl_bru_op;
  wire [1:0]       _decoder_io_exe_ctrl_sel_alu1;
  wire [1:0]       _decoder_io_exe_ctrl_sel_alu2;
  wire             _decoder_io_exe_ctrl_sel_jpc_i;
  wire             _decoder_io_exe_ctrl_sel_jpc_o;
  wire             _decoder_io_exe_ctrl_redir_inst;
  wire             _decoder_io_exe_ctrl_bru_inst;
  wire [3:0]       _decoder_io_exe_ctrl_mem_cmd;
  wire [1:0]       _decoder_io_exe_ctrl_sel_wb;
  wire             _decoder_io_exe_ctrl_wb_en;
  wire [2:0]       _decoder_io_exe_ctrl_sel_imm;
  wire             _decoder_io_exe_ctrl_is_w;
  wire             _decoder_io_exe_ctrl_mul_valid;
  wire [2:0]       _decoder_io_exe_ctrl_mul_op;
  wire             _decoder_io_exe_ctrl_div_valid;
  wire [2:0]       _decoder_io_exe_ctrl_div_op;
  wire [11:0]      _decoder_io_exe_ctrl_csr_addr;
  wire [2:0]       _decoder_io_exe_ctrl_csr_cmd;
  wire             _decoder_io_exe_ctrl_fencei;
  wire             _decoder_io_exe_ctrl_is_ecall;
  wire             _decoder_io_exe_ctrl_is_ebreak;
  wire             _decoder_io_exe_ctrl_is_mret;
  wire             _decoder_io_exe_ctrl_is_sret;
  wire             _decoder_io_exe_ctrl_is_wfi;
  wire             _decoder_io_exe_ctrl_is_sfence_vma;
  wire [2:0]       _decoder_io_exe_ctrl_mem_op;
  wire [3:0]       _decoder_io_exe_ctrl_amo_func;
  wire             _decoder_io_exe_ctrl_amo_aq;
  wire             _decoder_io_exe_ctrl_amo_rl;
  wire             _decoder_io_illegal_inst;
  reg              ex_valid;
  reg  [63:0]      ex_pc;
  reg  [31:0]      ex_inst;
  reg  [31:0]      ex_rawInst;
  reg  [2:0]       ex_instLen;
  reg              ex_instruction_access_fault;
  reg              ex_instruction_page_fault;
  reg              ex_instruction_fault_second_parcel;
  reg              ex_illegal_inst;
  reg              ex_is_ecall;
  reg              ex_is_ebreak;
  reg              ex_is_mret;
  reg              ex_is_sret;
  reg              ex_is_wfi;
  reg  [1:0]       ex_pred_predType;
  reg              ex_pred_predTaken;
  reg  [63:0]      ex_pred_predPc;
  reg  [7:0]       ex_pred_phtIdx;
  reg  [3:0]       ex_ctrl_alu_op;
  reg  [2:0]       ex_ctrl_bru_op;
  reg  [1:0]       ex_ctrl_sel_alu1;
  reg  [1:0]       ex_ctrl_sel_alu2;
  reg              ex_ctrl_sel_jpc_i;
  reg              ex_ctrl_sel_jpc_o;
  reg              ex_ctrl_redir_inst;
  reg              ex_ctrl_bru_inst;
  reg  [3:0]       ex_ctrl_mem_cmd;
  reg  [1:0]       ex_ctrl_sel_wb;
  reg              ex_ctrl_wb_en;
  reg              ex_ctrl_is_w;
  reg              ex_ctrl_mul_valid;
  reg  [2:0]       ex_ctrl_mul_op;
  reg              ex_ctrl_div_valid;
  reg  [2:0]       ex_ctrl_div_op;
  reg  [11:0]      ex_ctrl_csr_addr;
  reg  [2:0]       ex_ctrl_csr_cmd;
  reg              ex_ctrl_fencei;
  reg              ex_ctrl_is_sfence_vma;
  reg  [2:0]       ex_ctrl_mem_op;
  reg  [3:0]       ex_ctrl_amo_func;
  reg              ex_ctrl_amo_aq;
  reg              ex_ctrl_amo_rl;
  reg              ex_estop;
  reg  [4:0]       ex_rs1_addr;
  reg  [4:0]       ex_rs2_addr;
  reg  [4:0]       ex_rd_addr;
  reg  [63:0]      ex_rs1_data;
  reg  [63:0]      ex_rs2_data;
  reg  [63:0]      ex_imm;
  reg              exFp_valid;
  reg              exFp_fpuValid;
  reg  [1:0]       exFp_localOp;
  reg              exFp_isLoad;
  reg              exFp_isStore;
  reg              exFp_isDouble;
  reg              exFp_writesFpr;
  reg              exFp_writesGpr;
  reg              exFp_usesGpr1;
  reg  [3:0]       exFp_operation;
  reg              exFp_opMod;
  reg  [2:0]       exFp_srcFmt;
  reg  [2:0]       exFp_dstFmt;
  reg  [1:0]       exFp_intFmt;
  reg  [2:0]       exFp_rm;
  reg              exFp_usesArchitecturalRm;
  reg  [63:0]      exFpr_0;
  reg  [63:0]      exFpr_1;
  reg  [63:0]      exFpr_2;
  reg              mem_valid;
  reg  [63:0]      mem_pc;
  reg  [63:0]      mem_nextPc;
  reg  [31:0]      mem_inst;
  reg  [31:0]      mem_rawInst;
  reg  [2:0]       mem_instLen;
  reg              mem_rd_isFp;
  reg  [4:0]       mem_rd_idx;
  reg              mem_writes;
  reg  [63:0]      mem_data;
  reg  [63:0]      mem_address;
  reg  [63:0]      mem_storeData;
  reg              mem_mem;
  reg              mem_load;
  reg              mem_mul;
  reg              mem_div;
  reg              mem_fp;
  reg              mem_serial;
  reg              mem_fencei;
  reg              mem_sfence;
  reg              mem_wfi;
  reg              mem_estop;
  reg              mem_mret;
  reg              mem_sret;
  reg              mem_exception;
  reg  [63:0]      mem_cause;
  reg  [63:0]      mem_tval;
  reg  [11:0]      mem_csrAddr;
  reg  [2:0]       mem_csrCmd;
  reg  [63:0]      mem_csrSource;
  reg              mem_csrWrite;
  reg  [4:0]       mem_rs1;
  reg  [4:0]       mem_rs2;
  reg              mem_predictionMiss;
  reg              wb_valid;
  reg  [63:0]      wb_pc;
  reg  [63:0]      wb_nextPc;
  reg  [31:0]      wb_inst;
  reg  [31:0]      wb_rawInst;
  reg  [2:0]       wb_instLen;
  reg              wb_rd_isFp;
  reg  [4:0]       wb_rd_idx;
  reg              wb_writes;
  reg  [63:0]      wb_data;
  reg  [63:0]      wb_address;
  reg  [63:0]      wb_storeData;
  reg              wb_mem;
  reg              wb_load;
  reg              wb_mul;
  reg              wb_div;
  reg              wb_fp;
  reg              wb_serial;
  reg              wb_fencei;
  reg              wb_sfence;
  reg              wb_wfi;
  reg              wb_estop;
  reg              wb_mret;
  reg              wb_sret;
  reg              wb_exception;
  reg  [63:0]      wb_cause;
  reg  [63:0]      wb_tval;
  reg  [11:0]      wb_csrAddr;
  reg  [2:0]       wb_csrCmd;
  reg  [63:0]      wb_csrSource;
  reg              wb_csrWrite;
  reg  [63:0]      wb_csrData;
  reg  [4:0]       wb_rs1;
  reg  [4:0]       wb_rs2;
  reg              wb_predictionMiss;
  reg              sleeping;
  reg              stopped;
  reg              sfenceSent;
  reg  [63:0]      nextPc;
  wire             _mem_serial_T = ex_ctrl_fencei | ex_ctrl_is_sfence_vma;
  wire             _oldCsrUsesRs1_T = _decoder_io_exe_ctrl_sel_alu1 == 2'h0;
  wire             gpr2Used =
    ~_fpDecoder_io_ctrl_valid
    & (_decoder_io_exe_ctrl_sel_alu2 == 2'h0 | _decoder_io_exe_ctrl_bru_inst
       | _decoder_io_exe_ctrl_mem_op == 3'h1 | _decoder_io_exe_ctrl_mem_op == 3'h3
       | _decoder_io_exe_ctrl_mem_op == 3'h4 | _decoder_io_exe_ctrl_is_sfence_vma);
  wire             scoreboard_io_operands_0_used =
    (_fpDecoder_io_ctrl_valid
       ? _fpDecoder_io_ctrl_usesGpr1
       : _oldCsrUsesRs1_T
         & ~((|_decoder_io_exe_ctrl_csr_cmd) & _decoder_io_exe_ctrl_csr_cmd[2])
         | _decoder_io_exe_ctrl_bru_inst | _decoder_io_exe_ctrl_sel_jpc_i
         | _decoder_io_exe_ctrl_is_sfence_vma) | _fpDecoder_io_ctrl_usesFpr1;
  wire             scoreboard_io_operands_1_used = gpr2Used | _fpDecoder_io_ctrl_usesFpr2;
  wire             _wbResponse_T = wb_valid & wb_mem;
  wire             wbResponse = _wbResponse_T & io_l1d_resp_valid;
  wire             wbMemExc = wbResponse & io_l1d_resp_bits_kind == 2'h2;
  wire             wbExc = wb_valid & (wb_exception | wbMemExc);
  wire             serialWait =
    wb_valid & ~wb_exception
    & (wb_fencei & ~io_l1d_drained | wb_sfence & (~sfenceSent | ~io_mmuIdle) | wb_estop
       & ((|{_scoreboard_io_gprBusy, _scoreboard_io_fprBusy})
          | _fpUnit_io_committedFlagsOnly));
  wire             downHold = io_l1d_s2Hold | serialWait;
  wire             wbCanLeave =
    wb_valid & ~downHold & ~_writeback_io_hartFatal & ~stopped;
  wire             wbCommit = wbCanLeave & ~wbExc;
  wire             interrupt =
    _csrFile_io_interruptPending & ~ex_valid & ~mem_valid & ~wb_valid & ~io_l1d_mmioBusy
    & ~_writeback_io_hartFatal & ~stopped;
  wire             xret = wbCommit & (wb_mret | wb_sret);
  wire             _csrFile_io_trap_valid_T = wbCanLeave & wbExc;
  wire             _wbKill_T_5 = wbCommit & wb_wfi;
  wire             wbKill =
    _csrFile_io_trap_valid_T | interrupt | wbCommit & (wb_fencei | wb_sfence) | xret
    | wbCommit & wb_csrWrite & wb_csrAddr == 12'h180 | _wbKill_T_5;
  wire             _scoreboard_io_pipe_2_valid_T = wb_mul | wb_div;
  wire [1:0]       _scoreboard_io_pipe_2_bits_source_T = {1'h1, ~wb_mul};
  wire             exLegal =
    ex_valid & ~ex_illegal_inst & ~ex_instruction_access_fault
    & ~ex_instruction_page_fault;
  wire             exMem =
    exLegal
    & (ex_ctrl_mem_cmd != 4'hB | exFp_isLoad | exFp_isStore | ex_inst[6:0] == 7'hF
       & ~ex_ctrl_fencei);
  wire             exMul = exLegal & ex_ctrl_mul_valid & (|ex_rd_addr);
  wire             exDiv = exLegal & ex_ctrl_div_valid & (|ex_rd_addr);
  wire             exFpLong = exLegal & exFp_fpuValid;
  wire             exBank = exFp_valid & exFp_writesFpr;
  wire             exWrites =
    exFp_valid ? exFp_writesFpr | exFp_writesGpr : ex_ctrl_wb_en;
  wire             _exFprRead_fromW2_T_4 = ex_rs1_addr == _writeback_io_w2_bits_rd_idx;
  wire             exR1_fromW2 =
    _writeback_io_w2_valid & ~_writeback_io_w2_bits_rd_isFp
    & (|_writeback_io_w2_bits_rd_idx) & _exFprRead_fromW2_T_4;
  wire             _ordinaryHazard_T_58 = wb_valid & wb_writes;
  wire             _exFprRead_fromWb_T_13 = ex_rs1_addr == wb_rd_idx;
  wire             exR1_fromWb =
    _ordinaryHazard_T_58 & ~wb_mem & ~wb_mul & ~wb_div & ~wb_fp & ~wb_rd_isFp
    & (|wb_rd_idx) & _exFprRead_fromWb_T_13;
  wire             _ordinaryHazard_T_32 = mem_valid & mem_writes;
  wire             _exFprRead_fromMem_T_43 = mem_csrCmd == 3'h0;
  wire             _exFprRead_fromMem_T_15 = ex_rs1_addr == mem_rd_idx;
  wire             exR1_fromMem =
    _ordinaryHazard_T_32 & ~mem_mem & ~mem_mul & ~mem_div & ~mem_fp
    & _exFprRead_fromMem_T_43 & ~mem_rd_isFp & (|mem_rd_idx) & _exFprRead_fromMem_T_15;
  wire [63:0]      _exR1_T_1 =
    exR1_fromWb ? wb_data : exR1_fromW2 ? _writeback_io_w2_bits_data : ex_rs1_data;
  wire [63:0]      exR1 = exR1_fromMem ? mem_data : _exR1_T_1;
  wire             _exFprRead_fromW2_T_10 = ex_rs2_addr == _writeback_io_w2_bits_rd_idx;
  wire             exR2_fromW2 =
    _writeback_io_w2_valid & ~_writeback_io_w2_bits_rd_isFp
    & (|_writeback_io_w2_bits_rd_idx) & _exFprRead_fromW2_T_10;
  wire             _exFprRead_fromWb_T_28 = ex_rs2_addr == wb_rd_idx;
  wire             exR2_fromWb =
    _ordinaryHazard_T_58 & ~wb_mem & ~wb_mul & ~wb_div & ~wb_fp & ~wb_rd_isFp
    & (|wb_rd_idx) & _exFprRead_fromWb_T_28;
  wire             _exFprRead_fromMem_T_32 = ex_rs2_addr == mem_rd_idx;
  wire             exR2_fromMem =
    _ordinaryHazard_T_32 & ~mem_mem & ~mem_mul & ~mem_div & ~mem_fp
    & _exFprRead_fromMem_T_43 & ~mem_rd_isFp & (|mem_rd_idx) & _exFprRead_fromMem_T_32;
  wire [63:0]      exR2 =
    exR2_fromMem
      ? mem_data
      : exR2_fromWb ? wb_data : exR2_fromW2 ? _writeback_io_w2_bits_data : ex_rs2_data;
  wire             exFprRead_fromW2 =
    _writeback_io_w2_valid & _writeback_io_w2_bits_rd_isFp & _exFprRead_fromW2_T_4;
  wire             exFprRead_fromWb =
    _ordinaryHazard_T_58 & ~wb_mem & ~wb_mul & ~wb_div & ~wb_fp & wb_rd_isFp
    & _exFprRead_fromWb_T_13;
  wire             exFprRead_fromMem =
    _ordinaryHazard_T_32 & ~mem_mem & ~mem_mul & ~mem_div & ~mem_fp
    & _exFprRead_fromMem_T_43 & mem_rd_isFp & _exFprRead_fromMem_T_15;
  wire [63:0]      _exFprRead_T_1 =
    exFprRead_fromWb ? wb_data : exFprRead_fromW2 ? _writeback_io_w2_bits_data : exFpr_0;
  wire [63:0]      exFprRead_0 = exFprRead_fromMem ? mem_data : _exFprRead_T_1;
  wire             exFprRead_fromW2_1 =
    _writeback_io_w2_valid & _writeback_io_w2_bits_rd_isFp & _exFprRead_fromW2_T_10;
  wire             exFprRead_fromWb_1 =
    _ordinaryHazard_T_58 & ~wb_mem & ~wb_mul & ~wb_div & ~wb_fp & wb_rd_isFp
    & _exFprRead_fromWb_T_28;
  wire             exFprRead_fromMem_1 =
    _ordinaryHazard_T_32 & ~mem_mem & ~mem_mul & ~mem_div & ~mem_fp
    & _exFprRead_fromMem_T_43 & mem_rd_isFp & _exFprRead_fromMem_T_32;
  wire [63:0]      exFprRead_1 =
    exFprRead_fromMem_1
      ? mem_data
      : exFprRead_fromWb_1
          ? wb_data
          : exFprRead_fromW2_1 ? _writeback_io_w2_bits_data : exFpr_1;
  wire             exFprRead_fromW2_2 =
    _writeback_io_w2_valid & _writeback_io_w2_bits_rd_isFp
    & ex_inst[31:27] == _writeback_io_w2_bits_rd_idx;
  wire             exFprRead_fromWb_2 =
    _ordinaryHazard_T_58 & ~wb_mem & ~wb_mul & ~wb_div & ~wb_fp & wb_rd_isFp
    & ex_inst[31:27] == wb_rd_idx;
  wire             exFprRead_fromMem_2 =
    _ordinaryHazard_T_32 & ~mem_mem & ~mem_mul & ~mem_div & ~mem_fp
    & _exFprRead_fromMem_T_43 & mem_rd_isFp & ex_inst[31:27] == mem_rd_idx;
  wire [3:0][63:0] _GEN = {{64'h0}, {64'h0}, {ex_pc}, {exR1}};
  wire [63:0]      _GEN_0 = {61'h0, ex_instLen};
  wire [3:0][63:0] _GEN_1 = {{64'h0}, {_GEN_0}, {ex_imm}, {exR2}};
  wire             taken = ex_ctrl_bru_inst ? _bru_io_take_branch : ex_ctrl_redir_inst;
  wire [63:0]      exNext = taken ? _jau_io_jmp_addr : ex_pc + _GEN_0;
  wire [63:0]      _address_T_3 =
    exR1
    + (ex_ctrl_mem_op == 3'h2 | ex_ctrl_mem_op == 3'h3 | ex_ctrl_mem_op == 3'h4
         ? 64'h0
         : exFp_isLoad | exFp_isStore
             ? {{52{ex_inst[31]}},
                exFp_isStore ? {ex_inst[31:25], ex_inst[11:7]} : ex_inst[31:20]}
             : ex_imm);
  wire             allowEx = ~downHold & ~wbKill & ~_writeback_io_hartFatal & ~stopped;
  wire             io_l1d_req_valid_0 = exMem & allowEx;
  wire [63:0]      io_l1d_req_bits_wdata_0 = exFp_isStore ? exFprRead_1 : exR2;
  wire             fpUnit_io_killUncommitted = wbKill | _writeback_io_hartFatal;
  wire             mulUnit_io_req_valid = exMul & allowEx;
  wire             _GEN_2 = ex_ctrl_mul_op != 3'h3;
  wire             _GEN_3 = ex_ctrl_mul_op == 3'h4;
  wire [63:0]      dividend =
    ex_ctrl_div_op[2] ? {{32{~(ex_ctrl_div_op[0]) & exR1[31]}}, exR1[31:0]} : exR1;
  wire [63:0]      divisor =
    ex_ctrl_div_op[2] ? {{32{~(ex_ctrl_div_op[0]) & exR2[31]}}, exR2[31:0]} : exR2;
  wire             negA = ~(ex_ctrl_div_op[0]) & dividend[63];
  wire             negB = ~(ex_ctrl_div_op[0]) & divisor[63];
  wire             byZero = divisor == 64'h0;
  wire [31:0]      fast =
    byZero
      ? (ex_ctrl_div_op[1] ? dividend[31:0] : 32'hFFFFFFFF)
      : ex_ctrl_div_op[1] ? 32'h0 : dividend[31:0];
  wire             divUnit_io_req_valid = exDiv & allowEx;
  wire             fpUnit_io_req_valid = exFpLong & allowEx;
  wire [63:0]      fp1 = exFp_usesGpr1 ? exR1 : exFprRead_0;
  wire             _fpUnit_io_req_bits_operandC_T = exFp_operation == 4'h2;
  wire             exAdvance =
    allowEx
    & ~(exMem & ~io_l1d_req_ready | exMul & ~_mulUnit_io_req_ready | exDiv
        & ~_divUnit_io_req_ready | exFpLong & ~_fpUnit_io_req_ready);
  wire             _train_T = exLegal & exAdvance;
  wire             branchRedirect =
    _train_T
    & (taken != ex_pred_predTaken | taken & ex_pred_predTaken
       & _jau_io_jmp_addr != ex_pred_predPc);
  wire             csrFile_io_commit_valid = wbCommit & (|wb_csrCmd);
  wire             csrFile_io_trap_valid = _csrFile_io_trap_valid_T | interrupt;
  wire             csrFile_io_mret_commit = wbCommit & wb_mret;
  wire             csrFile_io_sret_commit = wbCommit & wb_sret;
  wire             io_translationBlocked_0 = wb_valid & wb_sfence;
  wire             io_sfence_valid_0 =
    io_translationBlocked_0 & ~sfenceSent & io_l1d_drained & io_mmuIdle & ~wb_exception
    & ~_writeback_io_hartFatal;
  wire             io_frontendRedirect_valid_0 = wbKill | branchRedirect;
  reg              io_frontendRedirect_flush_REG;
  wire [63:0]      io_frontendRedirect_target_0 =
    csrFile_io_trap_valid
      ? _csrFile_io_trap_target
      : xret ? _csrFile_io_xret_target : wbKill ? wb_nextPc : exNext;
  reg              btb_valid;
  reg  [63:0]      btb_pc;
  reg  [63:0]      btb_target;
  reg  [1:0]       btb_predType;
  wire             train = _train_T & (ex_ctrl_bru_inst | ex_ctrl_redir_inst);
  wire             io_frontendGhrUpdate_valid_0 = train & ex_pred_predType == 2'h1;
  wire             io_frontendBtbUpdate_valid_0 =
    btb_valid & ~wbKill & ~downHold & ~_writeback_io_hartFatal;
  wire             oldCsrUsesRs1 =
    _oldCsrUsesRs1_T | _decoder_io_exe_ctrl_bru_inst | _decoder_io_exe_ctrl_is_sfence_vma
    | _decoder_io_exe_ctrl_sel_jpc_i | _decoder_io_exe_ctrl_csr_cmd == 3'h1
    | _decoder_io_exe_ctrl_csr_cmd == 3'h2 | _decoder_io_exe_ctrl_csr_cmd == 3'h3;
  wire             _ordinaryHazard_T_6 = ex_valid & exWrites;
  wire [5:0]       _GEN_4 = {exBank, ex_rd_addr};
  wire [5:0]       _GEN_5 = {mem_rd_isFp, mem_rd_idx};
  wire [5:0]       _GEN_6 = {wb_rd_isFp, wb_rd_idx};
  wire             io_fetchBuffer_ready_0 =
    exAdvance & ~_scoreboard_io_hazard
    & ~(ex_valid & (|ex_ctrl_csr_cmd) | mem_valid & (|mem_csrCmd) | wb_valid
        & wb_csrWrite)
    & ~((|_decoder_io_exe_ctrl_csr_cmd)
        & (_ordinaryHazard_T_6 & ~exBank & (|ex_rd_addr)
           & (oldCsrUsesRs1 & io_fetchBuffer_bits_inst[19:15] == ex_rd_addr | gpr2Used
              & io_fetchBuffer_bits_inst[24:20] == ex_rd_addr) | _ordinaryHazard_T_32
           & ~mem_rd_isFp & (|mem_rd_idx)
           & (oldCsrUsesRs1 & io_fetchBuffer_bits_inst[19:15] == mem_rd_idx | gpr2Used
              & io_fetchBuffer_bits_inst[24:20] == mem_rd_idx) | _ordinaryHazard_T_58
           & ~wb_rd_isFp & (|wb_rd_idx)
           & (oldCsrUsesRs1 & io_fetchBuffer_bits_inst[19:15] == wb_rd_idx | gpr2Used
              & io_fetchBuffer_bits_inst[24:20] == wb_rd_idx)))
    & ~(_ordinaryHazard_T_6 & (ex_ctrl_sel_wb == 2'h2 | exFp_valid)
        & (scoreboard_io_operands_0_used & _fpDecoder_io_ctrl_usesFpr1 == exBank
           & io_fetchBuffer_bits_inst[19:15] == ex_rd_addr & (|_GEN_4)
           | scoreboard_io_operands_1_used & _fpDecoder_io_ctrl_usesFpr2 == exBank
           & io_fetchBuffer_bits_inst[24:20] == ex_rd_addr & (|_GEN_4)
           | _fpDecoder_io_ctrl_usesFpr3 & exBank
           & io_fetchBuffer_bits_inst[31:27] == ex_rd_addr & (|_GEN_4))
        | _ordinaryHazard_T_32 & ((|mem_csrCmd) | mem_rd_isFp)
        & (scoreboard_io_operands_0_used & _fpDecoder_io_ctrl_usesFpr1 == mem_rd_isFp
           & io_fetchBuffer_bits_inst[19:15] == mem_rd_idx & (|_GEN_5)
           | scoreboard_io_operands_1_used & _fpDecoder_io_ctrl_usesFpr2 == mem_rd_isFp
           & io_fetchBuffer_bits_inst[24:20] == mem_rd_idx & (|_GEN_5)
           | _fpDecoder_io_ctrl_usesFpr3 & mem_rd_isFp
           & io_fetchBuffer_bits_inst[31:27] == mem_rd_idx & (|_GEN_5))
        | _ordinaryHazard_T_58 & ((|wb_csrCmd) | wb_rd_isFp)
        & (scoreboard_io_operands_0_used & _fpDecoder_io_ctrl_usesFpr1 == wb_rd_isFp
           & io_fetchBuffer_bits_inst[19:15] == wb_rd_idx & (|_GEN_6)
           | scoreboard_io_operands_1_used & _fpDecoder_io_ctrl_usesFpr2 == wb_rd_isFp
           & io_fetchBuffer_bits_inst[24:20] == wb_rd_idx & (|_GEN_6)
           | _fpDecoder_io_ctrl_usesFpr3 & wb_rd_isFp
           & io_fetchBuffer_bits_inst[31:27] == wb_rd_idx & (|_GEN_6)))
    & ~(ex_valid & (_mem_serial_T | ex_is_wfi | ex_estop) | mem_valid & mem_serial
        | wb_valid & wb_serial) & ~_writeback_io_idStarve & ~branchRedirect
    & ~_csrFile_io_interruptPending & ~sleeping & ~_writeback_io_hartFatal;
  wire             idLeave = io_fetchBuffer_ready_0 & io_fetchBuffer_valid;
  wire             _io_estop_T = wbCommit & wb_estop;
  wire             io_backendEvents_controlRetired =
    wbCommit & (wb_inst[6:0] == 7'h63 | wb_inst[6:0] == 7'h6F | wb_inst[6:0] == 7'h67);
  reg              pastDownHold;
  reg              pastKill;
  reg              pastActive;
  reg  [690:0]     heldMem;
  reg  [690:0]     heldWb;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      automatic logic _io_observe_fpIn_T = _fpUnit_io_req_ready & fpUnit_io_req_valid;
      automatic logic _io_observe_mulIn_T = _mulUnit_io_req_ready & mulUnit_io_req_valid;
      automatic logic _io_observe_divIn_T = _divUnit_io_req_ready & divUnit_io_req_valid;
      automatic logic _GEN_7 = io_l1d_req_ready & io_l1d_req_valid_0;
      automatic logic _GEN_8 = ~reset & downHold & wb_valid;
      if (pastActive & ~reset & pastDownHold & ~pastKill
          & ~({mem_valid,
               mem_pc,
               mem_nextPc,
               mem_inst,
               mem_rawInst,
               mem_instLen,
               mem_rd_isFp,
               mem_rd_idx,
               mem_writes,
               mem_data,
               mem_address,
               mem_storeData,
               mem_mem,
               mem_load,
               mem_mul,
               mem_div,
               mem_fp,
               mem_serial,
               mem_fencei,
               mem_sfence,
               mem_wfi,
               mem_estop,
               mem_mret,
               mem_sret,
               mem_exception,
               mem_cause,
               mem_tval,
               mem_csrAddr,
               mem_csrCmd,
               mem_csrSource,
               mem_csrWrite,
               64'h0,
               mem_rs1,
               mem_rs2,
               mem_predictionMiss} == heldMem
              & {wb_valid,
                 wb_pc,
                 wb_nextPc,
                 wb_inst,
                 wb_rawInst,
                 wb_instLen,
                 wb_rd_isFp,
                 wb_rd_idx,
                 wb_writes,
                 wb_data,
                 wb_address,
                 wb_storeData,
                 wb_mem,
                 wb_load,
                 wb_mul,
                 wb_div,
                 wb_fp,
                 wb_serial,
                 wb_fencei,
                 wb_sfence,
                 wb_wfi,
                 wb_estop,
                 wb_mret,
                 wb_sret,
                 wb_exception,
                 wb_cause,
                 wb_tval,
                 wb_csrAddr,
                 wb_csrCmd,
                 wb_csrSource,
                 wb_csrWrite,
                 wb_csrData,
                 wb_rs1,
                 wb_rs2,
                 wb_predictionMiss} == heldWb)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S09] held MEM/WB metadata changed\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _writeback_io_hartFatal
          & (idLeave | wbCommit | _GEN_7 | _io_observe_mulIn_T | _io_observe_divIn_T
             | _io_observe_fpIn_T)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [fatal] new issue or ordinary retirement\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~io_l1d_resp_valid | _wbResponse_T)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S15] L1D resp is not aligned to WB\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & io_l1d_resp_valid & io_l1d_s2Hold) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S15] simultaneous hold and decision\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~(mem_valid & mem_mem & downHold) | io_l1d_s2Hold)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [stall direction] MEM memory held without s2Hold\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~serialWait | ~ex_valid & ~mem_valid)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [stall direction] serial wait with younger pipeline entries\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & ~(~wbKill
              | ~(_GEN_7 | _io_observe_mulIn_T | _io_observe_divIn_T
                  | _io_observe_fpIn_T))) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S13] younger request survived WB kill\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (_GEN_8
          & (io_frontendBtbUpdate_valid_0 | io_frontendGhrUpdate_valid_0
             | io_frontendRedirect_valid_0 | csrFile_io_commit_valid
             | csrFile_io_trap_valid | csrFile_io_mret_commit
             | csrFile_io_sret_commit)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S09] control side effect while WB held\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (_GEN_8
          & ~(~io_sfence_valid_0 | wb_sfence & ~sfenceSent & io_l1d_drained
              & io_mmuIdle)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S09] SFENCE repeated or issued before drain/idle\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~downHold | ~wbCommit)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S09] held WB retired\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~wbCommit | ~wb_mem | io_l1d_resp_valid)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S15] memory retired without S2 decision\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    if (reset) begin
      ex_valid <= 1'h0;
      ex_pc <= 64'h0;
      ex_inst <= 32'h0;
      ex_rawInst <= 32'h0;
      ex_instLen <= 3'h0;
      ex_instruction_access_fault <= 1'h0;
      ex_instruction_page_fault <= 1'h0;
      ex_instruction_fault_second_parcel <= 1'h0;
      ex_illegal_inst <= 1'h0;
      ex_is_ecall <= 1'h0;
      ex_is_ebreak <= 1'h0;
      ex_is_mret <= 1'h0;
      ex_is_sret <= 1'h0;
      ex_is_wfi <= 1'h0;
      ex_pred_predType <= 2'h0;
      ex_pred_predTaken <= 1'h0;
      ex_pred_predPc <= 64'h0;
      ex_pred_phtIdx <= 8'h0;
      ex_ctrl_alu_op <= 4'h0;
      ex_ctrl_bru_op <= 3'h0;
      ex_ctrl_sel_alu1 <= 2'h0;
      ex_ctrl_sel_alu2 <= 2'h0;
      ex_ctrl_sel_jpc_i <= 1'h0;
      ex_ctrl_sel_jpc_o <= 1'h0;
      ex_ctrl_redir_inst <= 1'h0;
      ex_ctrl_bru_inst <= 1'h0;
      ex_ctrl_mem_cmd <= 4'h0;
      ex_ctrl_sel_wb <= 2'h0;
      ex_ctrl_wb_en <= 1'h0;
      ex_ctrl_is_w <= 1'h0;
      ex_ctrl_mul_valid <= 1'h0;
      ex_ctrl_mul_op <= 3'h0;
      ex_ctrl_div_valid <= 1'h0;
      ex_ctrl_div_op <= 3'h0;
      ex_ctrl_csr_addr <= 12'h0;
      ex_ctrl_csr_cmd <= 3'h0;
      ex_ctrl_fencei <= 1'h0;
      ex_ctrl_is_sfence_vma <= 1'h0;
      ex_ctrl_mem_op <= 3'h0;
      ex_ctrl_amo_func <= 4'h0;
      ex_ctrl_amo_aq <= 1'h0;
      ex_ctrl_amo_rl <= 1'h0;
      ex_estop <= 1'h0;
      ex_rs1_addr <= 5'h0;
      ex_rs2_addr <= 5'h0;
      ex_rd_addr <= 5'h0;
      ex_rs1_data <= 64'h0;
      ex_rs2_data <= 64'h0;
      ex_imm <= 64'h0;
      exFp_valid <= 1'h0;
      exFp_fpuValid <= 1'h0;
      exFp_localOp <= 2'h0;
      exFp_isLoad <= 1'h0;
      exFp_isStore <= 1'h0;
      exFp_isDouble <= 1'h0;
      exFp_writesFpr <= 1'h0;
      exFp_writesGpr <= 1'h0;
      exFp_usesGpr1 <= 1'h0;
      exFp_operation <= 4'h0;
      exFp_opMod <= 1'h0;
      exFp_srcFmt <= 3'h0;
      exFp_dstFmt <= 3'h0;
      exFp_intFmt <= 2'h0;
      exFp_rm <= 3'h0;
      exFp_usesArchitecturalRm <= 1'h0;
      exFpr_0 <= 64'h0;
      exFpr_1 <= 64'h0;
      exFpr_2 <= 64'h0;
      mem_valid <= 1'h0;
      mem_pc <= 64'h0;
      mem_nextPc <= 64'h0;
      mem_inst <= 32'h0;
      mem_rawInst <= 32'h0;
      mem_instLen <= 3'h0;
      mem_rd_isFp <= 1'h0;
      mem_rd_idx <= 5'h0;
      mem_writes <= 1'h0;
      mem_data <= 64'h0;
      mem_address <= 64'h0;
      mem_storeData <= 64'h0;
      mem_mem <= 1'h0;
      mem_load <= 1'h0;
      mem_mul <= 1'h0;
      mem_div <= 1'h0;
      mem_fp <= 1'h0;
      mem_serial <= 1'h0;
      mem_fencei <= 1'h0;
      mem_sfence <= 1'h0;
      mem_wfi <= 1'h0;
      mem_estop <= 1'h0;
      mem_mret <= 1'h0;
      mem_sret <= 1'h0;
      mem_exception <= 1'h0;
      mem_cause <= 64'h0;
      mem_tval <= 64'h0;
      mem_csrAddr <= 12'h0;
      mem_csrCmd <= 3'h0;
      mem_csrSource <= 64'h0;
      mem_csrWrite <= 1'h0;
      mem_rs1 <= 5'h0;
      mem_rs2 <= 5'h0;
      mem_predictionMiss <= 1'h0;
      wb_valid <= 1'h0;
      wb_pc <= 64'h0;
      wb_nextPc <= 64'h0;
      wb_inst <= 32'h0;
      wb_rawInst <= 32'h0;
      wb_instLen <= 3'h0;
      wb_rd_isFp <= 1'h0;
      wb_rd_idx <= 5'h0;
      wb_writes <= 1'h0;
      wb_data <= 64'h0;
      wb_address <= 64'h0;
      wb_storeData <= 64'h0;
      wb_mem <= 1'h0;
      wb_load <= 1'h0;
      wb_mul <= 1'h0;
      wb_div <= 1'h0;
      wb_fp <= 1'h0;
      wb_serial <= 1'h0;
      wb_fencei <= 1'h0;
      wb_sfence <= 1'h0;
      wb_wfi <= 1'h0;
      wb_estop <= 1'h0;
      wb_mret <= 1'h0;
      wb_sret <= 1'h0;
      wb_exception <= 1'h0;
      wb_cause <= 64'h0;
      wb_tval <= 64'h0;
      wb_csrAddr <= 12'h0;
      wb_csrCmd <= 3'h0;
      wb_csrSource <= 64'h0;
      wb_csrWrite <= 1'h0;
      wb_csrData <= 64'h0;
      wb_rs1 <= 5'h0;
      wb_rs2 <= 5'h0;
      wb_predictionMiss <= 1'h0;
      sleeping <= 1'h0;
      stopped <= 1'h0;
      sfenceSent <= 1'h0;
      nextPc <= 64'h0;
      io_frontendRedirect_flush_REG <= 1'h0;
      btb_valid <= 1'h0;
      btb_pc <= 64'h0;
      btb_target <= 64'h0;
      btb_predType <= 2'h0;
      pastDownHold <= 1'h0;
      pastKill <= 1'h0;
      pastActive <= 1'h0;
    end
    else begin
      automatic logic _GEN_9;
      automatic logic _GEN_10 = reset | wbKill;
      automatic logic _GEN_11 = _GEN_10 | branchRedirect | _writeback_io_hartFatal;
      automatic logic _GEN_12 = _GEN_11 | ~idLeave;
      automatic logic _GEN_13 = _GEN_10 | _writeback_io_hartFatal;
      automatic logic _GEN_14 = _GEN_13 | downHold;
      _GEN_9 = ~downHold | wbKill;
      ex_valid <= ~_GEN_11 & (exAdvance ? idLeave : ex_valid);
      if (_GEN_12) begin
      end
      else begin
        ex_pc <= io_fetchBuffer_bits_pc;
        ex_inst <= io_fetchBuffer_bits_inst;
        ex_rawInst <= io_fetchBuffer_bits_rawInst;
        ex_instLen <= io_fetchBuffer_bits_instLen == 3'h2 ? 3'h2 : 3'h4;
        ex_instruction_access_fault <= io_fetchBuffer_bits_instructionAccessFault;
        ex_instruction_page_fault <= io_fetchBuffer_bits_instructionPageFault;
        ex_instruction_fault_second_parcel <=
          io_fetchBuffer_bits_instructionFaultSecondParcel;
        ex_illegal_inst <=
          io_fetchBuffer_bits_illegalCompressed | _decoder_io_illegal_inst
          & ~_fpDecoder_io_ctrl_valid | _fpDecoder_io_ctrl_valid & ~_csrFile_io_fp_enabled
          | _decoder_io_exe_ctrl_is_mret & _csrFile_io_mret_illegal
          | _decoder_io_exe_ctrl_is_sret & _csrFile_io_sret_illegal
          | _decoder_io_exe_ctrl_is_wfi & _csrFile_io_wfi_illegal
          | _decoder_io_exe_ctrl_is_sfence_vma & _csrFile_io_sfence_vma_illegal;
        ex_is_ecall <= _decoder_io_exe_ctrl_is_ecall;
        ex_is_ebreak <= _decoder_io_exe_ctrl_is_ebreak;
        ex_is_mret <= _decoder_io_exe_ctrl_is_mret;
        ex_is_sret <= _decoder_io_exe_ctrl_is_sret;
        ex_is_wfi <= _decoder_io_exe_ctrl_is_wfi;
        ex_pred_predType <= io_fetchBuffer_bits_pred_predType;
        ex_pred_predTaken <= io_fetchBuffer_bits_pred_predTaken;
        ex_pred_predPc <= io_fetchBuffer_bits_pred_predPc;
        ex_pred_phtIdx <= io_fetchBuffer_bits_pred_phtIdx;
        ex_ctrl_alu_op <= _decoder_io_exe_ctrl_alu_op;
        ex_ctrl_bru_op <= _decoder_io_exe_ctrl_bru_op;
        ex_ctrl_sel_alu1 <= _decoder_io_exe_ctrl_sel_alu1;
        ex_ctrl_sel_alu2 <= _decoder_io_exe_ctrl_sel_alu2;
        ex_ctrl_sel_jpc_i <= _decoder_io_exe_ctrl_sel_jpc_i;
        ex_ctrl_sel_jpc_o <= _decoder_io_exe_ctrl_sel_jpc_o;
        ex_ctrl_redir_inst <= _decoder_io_exe_ctrl_redir_inst;
        ex_ctrl_bru_inst <= _decoder_io_exe_ctrl_bru_inst;
        ex_ctrl_mem_cmd <= _decoder_io_exe_ctrl_mem_cmd;
        ex_ctrl_sel_wb <= _decoder_io_exe_ctrl_sel_wb;
        ex_ctrl_wb_en <= _decoder_io_exe_ctrl_wb_en;
        ex_ctrl_is_w <= _decoder_io_exe_ctrl_is_w;
        ex_ctrl_mul_valid <= _decoder_io_exe_ctrl_mul_valid;
        ex_ctrl_mul_op <= _decoder_io_exe_ctrl_mul_op;
        ex_ctrl_div_valid <= _decoder_io_exe_ctrl_div_valid;
        ex_ctrl_div_op <= _decoder_io_exe_ctrl_div_op;
        ex_ctrl_csr_addr <= _decoder_io_exe_ctrl_csr_addr;
        ex_ctrl_csr_cmd <= _decoder_io_exe_ctrl_csr_cmd;
        ex_ctrl_fencei <= _decoder_io_exe_ctrl_fencei;
        ex_ctrl_is_sfence_vma <= _decoder_io_exe_ctrl_is_sfence_vma;
        ex_ctrl_mem_op <= _decoder_io_exe_ctrl_mem_op;
        ex_ctrl_amo_func <= _decoder_io_exe_ctrl_amo_func;
        ex_ctrl_amo_aq <= _decoder_io_exe_ctrl_amo_aq;
        ex_ctrl_amo_rl <= _decoder_io_exe_ctrl_amo_rl;
        ex_estop <= io_fetchBuffer_bits_inst == 32'h7FF00073;
        ex_rs1_addr <= io_fetchBuffer_bits_inst[19:15];
        ex_rs2_addr <= io_fetchBuffer_bits_inst[24:20];
        ex_rd_addr <= io_fetchBuffer_bits_inst[11:7];
      end
      if (~_GEN_11) begin
        if (exAdvance) begin
          if (idLeave) begin
            ex_rs1_data <= _regFile_io_rs1_data;
            ex_rs2_data <= _regFile_io_rs2_data;
            exFpr_0 <= _fpRegFile_io_rs1Data;
            exFpr_1 <= _fpRegFile_io_rs2Data;
            exFpr_2 <= _fpRegFile_io_rs3Data;
          end
        end
        else begin
          if (exR1_fromMem)
            ex_rs1_data <= mem_data;
          else if (exR1_fromWb)
            ex_rs1_data <= wb_data;
          else if (exR1_fromW2)
            ex_rs1_data <= _writeback_io_w2_bits_data;
          if (exR2_fromMem)
            ex_rs2_data <= mem_data;
          else if (exR2_fromWb)
            ex_rs2_data <= wb_data;
          else if (exR2_fromW2)
            ex_rs2_data <= _writeback_io_w2_bits_data;
          if (exFprRead_fromMem)
            exFpr_0 <= mem_data;
          else if (exFprRead_fromWb)
            exFpr_0 <= wb_data;
          else if (exFprRead_fromW2)
            exFpr_0 <= _writeback_io_w2_bits_data;
          if (exFprRead_fromMem_1)
            exFpr_1 <= mem_data;
          else if (exFprRead_fromWb_1)
            exFpr_1 <= wb_data;
          else if (exFprRead_fromW2_1)
            exFpr_1 <= _writeback_io_w2_bits_data;
          if (exFprRead_fromMem_2)
            exFpr_2 <= mem_data;
          else if (exFprRead_fromWb_2)
            exFpr_2 <= wb_data;
          else if (exFprRead_fromW2_2)
            exFpr_2 <= _writeback_io_w2_bits_data;
        end
      end
      if (_GEN_12) begin
      end
      else begin
        ex_imm <= _immGen_io_imm;
        exFp_valid <= _fpDecoder_io_ctrl_valid;
        exFp_fpuValid <= _fpDecoder_io_ctrl_fpuValid;
        exFp_localOp <= _fpDecoder_io_ctrl_localOp;
        exFp_isLoad <= _fpDecoder_io_ctrl_isLoad;
        exFp_isStore <= _fpDecoder_io_ctrl_isStore;
        exFp_isDouble <= _fpDecoder_io_ctrl_isDouble;
        exFp_writesFpr <= _fpDecoder_io_ctrl_writesFpr;
        exFp_writesGpr <= _fpDecoder_io_ctrl_writesGpr;
        exFp_usesGpr1 <= _fpDecoder_io_ctrl_usesGpr1;
        exFp_operation <= _fpDecoder_io_ctrl_operation;
        exFp_opMod <= _fpDecoder_io_ctrl_opMod;
        exFp_srcFmt <= _fpDecoder_io_ctrl_srcFmt;
        exFp_dstFmt <= _fpDecoder_io_ctrl_dstFmt;
        exFp_intFmt <= _fpDecoder_io_ctrl_intFmt;
        exFp_rm <= _fpDecoder_io_ctrl_rm;
        exFp_usesArchitecturalRm <= _fpDecoder_io_ctrl_usesArchitecturalRm;
      end
      mem_valid <= ~_GEN_13 & (downHold ? mem_valid : ex_valid & exAdvance);
      if (_GEN_14) begin
      end
      else begin
        automatic logic _mem_tval_T =
          ex_instruction_access_fault | ex_instruction_page_fault;
        mem_pc <= ex_pc;
        mem_nextPc <= exNext;
        mem_inst <= ex_inst;
        mem_rawInst <= ex_rawInst;
        mem_instLen <= ex_instLen;
        mem_rd_isFp <= exBank;
        mem_rd_idx <= ex_rd_addr;
        mem_writes <= exWrites;
        if (|exFp_localOp) begin
          if (exFp_localOp == 2'h1) begin
            if (exFp_isDouble) begin
              if (~exFprRead_fromMem)
                mem_data <= _exFprRead_T_1;
            end
            else
              mem_data <= {{32{exFprRead_0[31]}}, exFprRead_0[31:0]};
          end
          else if (exFp_isDouble) begin
            if (~exR1_fromMem)
              mem_data <= _exR1_T_1;
          end
          else
            mem_data <= {32'hFFFFFFFF, exR1[31:0]};
        end
        else
          mem_data <= _alu_io_alu_out;
        mem_address <= ex_ctrl_is_sfence_vma ? exR1 : _address_T_3;
        mem_storeData <= io_l1d_req_bits_wdata_0;
        mem_mem <= exMem;
        mem_load <=
          exMem & ~(exFp_isStore | ex_ctrl_mem_op == 3'h1 | ex_inst[6:0] == 7'hF);
        mem_mul <= exMul;
        mem_div <= exDiv;
        mem_fp <= exFpLong;
        mem_serial <= _mem_serial_T | ex_is_wfi | ex_estop;
        mem_fencei <= ex_ctrl_fencei;
        mem_sfence <= ex_ctrl_is_sfence_vma;
        mem_wfi <= ex_is_wfi;
        mem_estop <= ex_estop;
        mem_mret <= ex_is_mret;
        mem_sret <= ex_is_sret;
        mem_exception <= _mem_tval_T | ex_illegal_inst | ex_is_ecall | ex_is_ebreak;
        mem_cause <=
          {60'h0,
           ex_instruction_access_fault
             ? 4'h1
             : ex_instruction_page_fault
                 ? 4'hC
                 : ex_is_ebreak
                     ? 4'h3
                     : ex_is_ecall
                         ? (_csrFile_io_current_privilege == 2'h1
                              ? 4'h9
                              : _csrFile_io_current_privilege == 2'h0 ? 4'h8 : 4'hB)
                         : 4'h2};
        mem_tval <=
          _mem_tval_T
            ? ex_pc + {62'h0, ex_instruction_fault_second_parcel, 1'h0}
            : {32'h0, ex_illegal_inst ? ex_rawInst : 32'h0};
        mem_csrAddr <= ex_ctrl_csr_addr;
        mem_csrCmd <= ex_ctrl_csr_cmd;
        mem_csrSource <= ex_ctrl_csr_cmd[2] ? {59'h0, ex_rs1_addr} : exR1;
      end
      mem_csrWrite <= _GEN_14 & mem_csrWrite;
      if (_GEN_14) begin
      end
      else begin
        mem_rs1 <= ex_rs1_addr;
        mem_rs2 <= ex_rs2_addr;
        mem_predictionMiss <= branchRedirect;
      end
      wb_valid <= ~_GEN_13 & (downHold ? wb_valid : mem_valid);
      if (_GEN_14) begin
      end
      else begin
        automatic logic _GEN_15 = mem_valid & (|mem_csrCmd);
        automatic logic _GEN_16 = _GEN_15 & _csrFile_io_csr_illegal & ~mem_exception;
        wb_pc <= mem_pc;
        wb_nextPc <= mem_nextPc;
        wb_inst <= mem_inst;
        wb_rawInst <= mem_rawInst;
        wb_instLen <= mem_instLen;
        wb_rd_isFp <= mem_rd_isFp;
        wb_rd_idx <= mem_rd_idx;
        wb_writes <= mem_writes;
        wb_data <= _GEN_15 ? _csrFile_io_csr_old_data : mem_data;
        wb_address <= mem_address;
        wb_storeData <= mem_storeData;
        wb_mem <= mem_mem;
        wb_load <= mem_load;
        wb_mul <= mem_mul;
        wb_div <= mem_div;
        wb_fp <= mem_fp;
        wb_serial <= mem_serial;
        wb_fencei <= mem_fencei;
        wb_sfence <= mem_sfence;
        wb_wfi <= mem_wfi;
        wb_estop <= mem_estop;
        wb_mret <= mem_mret;
        wb_sret <= mem_sret;
        wb_exception <= _GEN_16 | mem_exception;
        wb_cause <= _GEN_16 ? 64'h2 : mem_cause;
        wb_tval <= _GEN_16 ? {32'h0, mem_rawInst} : mem_tval;
        wb_csrAddr <= mem_csrAddr;
        wb_csrCmd <= mem_csrCmd;
        wb_csrSource <= mem_csrSource;
        wb_csrWrite <= _GEN_15 ? _csrFile_io_csr_write_en : mem_csrWrite;
        wb_csrData <= _GEN_15 ? _csrFile_io_csr_new_data : 64'h0;
        wb_rs1 <= mem_rs1;
        wb_rs2 <= mem_rs2;
        wb_predictionMiss <= mem_predictionMiss;
      end
      sleeping <= ~_csrFile_io_wfiWakeup & (_wbKill_T_5 | sleeping);
      stopped <= _io_estop_T | stopped;
      sfenceSent <= ~wbCanLeave & (io_sfence_valid_0 | sfenceSent);
      if (reset)
        nextPc <= io_resetAddr;
      else if (wbKill)
        nextPc <= io_frontendRedirect_target_0;
      else if (wbCommit)
        nextPc <= wb_nextPc;
      io_frontendRedirect_flush_REG <= io_translationBlocked_0;
      btb_valid <=
        train
          ? ex_pred_predType == 2'h1 | ex_pred_predType == 2'h2 | (&ex_pred_predType)
            & branchRedirect
          : ~_GEN_9 & btb_valid;
      if (train) begin
        btb_pc <= ex_pc;
        btb_target <= _jau_io_jmp_addr;
        btb_predType <= ex_pred_predType;
      end
      else if (_GEN_9) begin
        btb_pc <= 64'h0;
        btb_target <= 64'h0;
        btb_predType <= 2'h0;
      end
      pastDownHold <= downHold;
      pastKill <= fpUnit_io_killUncommitted;
      pastActive <= ~reset;
    end
    heldMem <=
      {mem_valid,
       mem_pc,
       mem_nextPc,
       mem_inst,
       mem_rawInst,
       mem_instLen,
       mem_rd_isFp,
       mem_rd_idx,
       mem_writes,
       mem_data,
       mem_address,
       mem_storeData,
       mem_mem,
       mem_load,
       mem_mul,
       mem_div,
       mem_fp,
       mem_serial,
       mem_fencei,
       mem_sfence,
       mem_wfi,
       mem_estop,
       mem_mret,
       mem_sret,
       mem_exception,
       mem_cause,
       mem_tval,
       mem_csrAddr,
       mem_csrCmd,
       mem_csrSource,
       mem_csrWrite,
       64'h0,
       mem_rs1,
       mem_rs2,
       mem_predictionMiss};
    heldWb <=
      {wb_valid,
       wb_pc,
       wb_nextPc,
       wb_inst,
       wb_rawInst,
       wb_instLen,
       wb_rd_isFp,
       wb_rd_idx,
       wb_writes,
       wb_data,
       wb_address,
       wb_storeData,
       wb_mem,
       wb_load,
       wb_mul,
       wb_div,
       wb_fp,
       wb_serial,
       wb_fencei,
       wb_sfence,
       wb_wfi,
       wb_estop,
       wb_mret,
       wb_sret,
       wb_exception,
       wb_cause,
       wb_tval,
       wb_csrAddr,
       wb_csrCmd,
       wb_csrSource,
       wb_csrWrite,
       wb_csrData,
       wb_rs1,
       wb_rs2,
       wb_predictionMiss};
  end // always @(posedge)
  Decoder decoder (
    .io_inst                   (io_fetchBuffer_bits_inst),
    .io_exe_ctrl_alu_op        (_decoder_io_exe_ctrl_alu_op),
    .io_exe_ctrl_bru_op        (_decoder_io_exe_ctrl_bru_op),
    .io_exe_ctrl_sel_alu1      (_decoder_io_exe_ctrl_sel_alu1),
    .io_exe_ctrl_sel_alu2      (_decoder_io_exe_ctrl_sel_alu2),
    .io_exe_ctrl_sel_jpc_i     (_decoder_io_exe_ctrl_sel_jpc_i),
    .io_exe_ctrl_sel_jpc_o     (_decoder_io_exe_ctrl_sel_jpc_o),
    .io_exe_ctrl_redir_inst    (_decoder_io_exe_ctrl_redir_inst),
    .io_exe_ctrl_bru_inst      (_decoder_io_exe_ctrl_bru_inst),
    .io_exe_ctrl_mem_cmd       (_decoder_io_exe_ctrl_mem_cmd),
    .io_exe_ctrl_sel_wb        (_decoder_io_exe_ctrl_sel_wb),
    .io_exe_ctrl_wb_en         (_decoder_io_exe_ctrl_wb_en),
    .io_exe_ctrl_sel_imm       (_decoder_io_exe_ctrl_sel_imm),
    .io_exe_ctrl_is_w          (_decoder_io_exe_ctrl_is_w),
    .io_exe_ctrl_mul_valid     (_decoder_io_exe_ctrl_mul_valid),
    .io_exe_ctrl_mul_op        (_decoder_io_exe_ctrl_mul_op),
    .io_exe_ctrl_div_valid     (_decoder_io_exe_ctrl_div_valid),
    .io_exe_ctrl_div_op        (_decoder_io_exe_ctrl_div_op),
    .io_exe_ctrl_csr_addr      (_decoder_io_exe_ctrl_csr_addr),
    .io_exe_ctrl_csr_cmd       (_decoder_io_exe_ctrl_csr_cmd),
    .io_exe_ctrl_fencei        (_decoder_io_exe_ctrl_fencei),
    .io_exe_ctrl_is_ecall      (_decoder_io_exe_ctrl_is_ecall),
    .io_exe_ctrl_is_ebreak     (_decoder_io_exe_ctrl_is_ebreak),
    .io_exe_ctrl_is_mret       (_decoder_io_exe_ctrl_is_mret),
    .io_exe_ctrl_is_sret       (_decoder_io_exe_ctrl_is_sret),
    .io_exe_ctrl_is_wfi        (_decoder_io_exe_ctrl_is_wfi),
    .io_exe_ctrl_is_sfence_vma (_decoder_io_exe_ctrl_is_sfence_vma),
    .io_exe_ctrl_mem_op        (_decoder_io_exe_ctrl_mem_op),
    .io_exe_ctrl_amo_func      (_decoder_io_exe_ctrl_amo_func),
    .io_exe_ctrl_amo_aq        (_decoder_io_exe_ctrl_amo_aq),
    .io_exe_ctrl_amo_rl        (_decoder_io_exe_ctrl_amo_rl),
    .io_illegal_inst           (_decoder_io_illegal_inst)
  );
  BreezeFpDecoder fpDecoder (
    .io_inst                     (io_fetchBuffer_bits_inst),
    .io_ctrl_valid               (_fpDecoder_io_ctrl_valid),
    .io_ctrl_fpuValid            (_fpDecoder_io_ctrl_fpuValid),
    .io_ctrl_localOp             (_fpDecoder_io_ctrl_localOp),
    .io_ctrl_isLoad              (_fpDecoder_io_ctrl_isLoad),
    .io_ctrl_isStore             (_fpDecoder_io_ctrl_isStore),
    .io_ctrl_isDouble            (_fpDecoder_io_ctrl_isDouble),
    .io_ctrl_writesFpr           (_fpDecoder_io_ctrl_writesFpr),
    .io_ctrl_writesGpr           (_fpDecoder_io_ctrl_writesGpr),
    .io_ctrl_usesFpr1            (_fpDecoder_io_ctrl_usesFpr1),
    .io_ctrl_usesFpr2            (_fpDecoder_io_ctrl_usesFpr2),
    .io_ctrl_usesFpr3            (_fpDecoder_io_ctrl_usesFpr3),
    .io_ctrl_usesGpr1            (_fpDecoder_io_ctrl_usesGpr1),
    .io_ctrl_operation           (_fpDecoder_io_ctrl_operation),
    .io_ctrl_opMod               (_fpDecoder_io_ctrl_opMod),
    .io_ctrl_srcFmt              (_fpDecoder_io_ctrl_srcFmt),
    .io_ctrl_dstFmt              (_fpDecoder_io_ctrl_dstFmt),
    .io_ctrl_intFmt              (_fpDecoder_io_ctrl_intFmt),
    .io_ctrl_rm                  (_fpDecoder_io_ctrl_rm),
    .io_ctrl_usesArchitecturalRm (_fpDecoder_io_ctrl_usesArchitecturalRm)
  );
  ImmGen immGen (
    .io_inst     (io_fetchBuffer_bits_inst),
    .io_imm      (_immGen_io_imm),
    .io_type_sel (_decoder_io_exe_ctrl_sel_imm)
  );
  RegFile regFile (
    .clock       (clock),
    .reset       (reset),
    .io_rs1_addr (io_fetchBuffer_bits_inst[19:15]),
    .io_rs2_addr (io_fetchBuffer_bits_inst[24:20]),
    .io_rd_addr  (_writeback_io_gprWrite_bits_idx),
    .io_rd_data  (_writeback_io_gprWrite_bits_data),
    .io_rd_en    (_writeback_io_gprWrite_valid),
    .io_rs1_data (_regFile_io_rs1_data),
    .io_rs2_data (_regFile_io_rs2_data)
  );
  BreezeFpRegFile fpRegFile (
    .clock      (clock),
    .reset      (reset),
    .io_rs1Addr (io_fetchBuffer_bits_inst[19:15]),
    .io_rs2Addr (io_fetchBuffer_bits_inst[24:20]),
    .io_rs3Addr (io_fetchBuffer_bits_inst[31:27]),
    .io_rs1Data (_fpRegFile_io_rs1Data),
    .io_rs2Data (_fpRegFile_io_rs2Data),
    .io_rs3Data (_fpRegFile_io_rs3Data),
    .io_rdAddr  (_writeback_io_fprWrite_bits_idx),
    .io_rdData  (_writeback_io_fprWrite_bits_data),
    .io_rdEn    (_writeback_io_fprWrite_valid)
  );
  CSRFile csrFile (
    .clock                          (clock),
    .reset                          (reset),
    .io_csr_addr                    (mem_csrAddr),
    .io_csr_cmd                     (mem_valid & ~mem_exception ? mem_csrCmd : 3'h0),
    .io_csr_reg_data                (mem_csrSource),
    .io_csr_old_data                (_csrFile_io_csr_old_data),
    .io_csr_new_data                (_csrFile_io_csr_new_data),
    .io_csr_write_en                (_csrFile_io_csr_write_en),
    .io_rs1_id                      (mem_rs1),
    .io_rd_id                       (mem_rd_idx),
    .io_commit_valid                (csrFile_io_commit_valid),
    .io_commit_addr                 (wb_csrAddr),
    .io_commit_wdata                (wb_csrData),
    .io_commit_write_en             (wb_csrWrite),
    .io_fp_commit_valid             (_writeback_io_fpFlags_valid),
    .io_fp_flags                    (_writeback_io_fpFlags_bits),
    .io_frm                         (_csrFile_io_frm),
    .io_fp_enabled                  (_csrFile_io_fp_enabled),
    .io_retire_valid                (wbCommit),
    .io_hpmEvents_controlRetired    (io_backendEvents_controlRetired),
    .io_hpmEvents_controlTaken
      (io_backendEvents_controlRetired & wb_nextPc != wb_pc + {61'h0, wb_instLen}),
    .io_hpmEvents_predictionMiss    (io_backendEvents_controlRetired & wb_predictionMiss),
    .io_hpmEvents_icacheAccess      (io_hpmEvents_icacheAccess),
    .io_hpmEvents_icacheMiss        (io_hpmEvents_icacheMiss),
    .io_hpmEvents_dcacheAccess      (io_hpmEvents_dcacheAccess),
    .io_hpmEvents_dcacheMiss        (io_hpmEvents_dcacheMiss),
    .io_hpmEvents_dcacheUncached    (io_hpmEvents_dcacheUncached),
    .io_hpmEvents_memStallCycle     (io_l1d_s2Hold),
    .io_hpmEvents_loadUseStall
      (io_fetchBuffer_valid & ~idLeave & _scoreboard_io_sourceStall_0),
    .io_hpmEvents_mulSourceStall    (_scoreboard_io_sourceStall_2),
    .io_hpmEvents_divSourceStall    (_scoreboard_io_sourceStall_1),
    .io_hpmEvents_wbPortConflict    (_writeback_io_conflict),
    .io_machineTimerInterrupt       (io_machineTimerInterrupt),
    .io_machineSoftwareInterrupt    (io_machineSoftwareInterrupt),
    .io_machineExternalInterrupt    (|io_externalInterrupts),
    .io_supervisorExternalInterrupt (io_supervisorExternalInterrupt),
    .io_time                        (io_time),
    .io_trap_valid                  (csrFile_io_trap_valid),
    .io_trap_is_interrupt           (interrupt),
    .io_trap_cause
      (interrupt
         ? _csrFile_io_interruptCause
         : wbMemExc ? io_l1d_resp_bits_excCause : wb_cause),
    .io_trap_pc                     (interrupt ? nextPc : wb_pc),
    .io_trap_tval
      (interrupt ? 64'h0 : wbMemExc ? io_l1d_resp_bits_tval : wb_tval),
    .io_mret_commit                 (csrFile_io_mret_commit),
    .io_sret_commit                 (csrFile_io_sret_commit),
    .io_trap_target                 (_csrFile_io_trap_target),
    .io_xret_target                 (_csrFile_io_xret_target),
    .io_current_privilege           (_csrFile_io_current_privilege),
    .io_mret_illegal                (_csrFile_io_mret_illegal),
    .io_sret_illegal                (_csrFile_io_sret_illegal),
    .io_wfi_illegal                 (_csrFile_io_wfi_illegal),
    .io_sfence_vma_illegal          (_csrFile_io_sfence_vma_illegal),
    .io_mmu_context_satp            (io_mmuContext_satp),
    .io_mmu_context_privilege       (_csrFile_io_mmu_context_privilege),
    .io_mmu_context_mprv            (_csrFile_io_mmu_context_mprv),
    .io_mmu_context_mpp             (_csrFile_io_mmu_context_mpp),
    .io_mmu_context_sum             (io_mmuContext_sum),
    .io_mmu_context_mxr             (io_mmuContext_mxr),
    .io_mmu_context_pmpcfg_0        (_csrFile_io_mmu_context_pmpcfg_0),
    .io_mmu_context_pmpcfg_1        (_csrFile_io_mmu_context_pmpcfg_1),
    .io_mmu_context_pmpcfg_2        (_csrFile_io_mmu_context_pmpcfg_2),
    .io_mmu_context_pmpcfg_3        (_csrFile_io_mmu_context_pmpcfg_3),
    .io_mmu_context_pmpcfg_4        (_csrFile_io_mmu_context_pmpcfg_4),
    .io_mmu_context_pmpcfg_5        (_csrFile_io_mmu_context_pmpcfg_5),
    .io_mmu_context_pmpcfg_6        (_csrFile_io_mmu_context_pmpcfg_6),
    .io_mmu_context_pmpcfg_7        (_csrFile_io_mmu_context_pmpcfg_7),
    .io_mmu_context_pmpaddr_0       (_csrFile_io_mmu_context_pmpaddr_0),
    .io_mmu_context_pmpaddr_1       (_csrFile_io_mmu_context_pmpaddr_1),
    .io_mmu_context_pmpaddr_2       (_csrFile_io_mmu_context_pmpaddr_2),
    .io_mmu_context_pmpaddr_3       (_csrFile_io_mmu_context_pmpaddr_3),
    .io_mmu_context_pmpaddr_4       (_csrFile_io_mmu_context_pmpaddr_4),
    .io_mmu_context_pmpaddr_5       (_csrFile_io_mmu_context_pmpaddr_5),
    .io_mmu_context_pmpaddr_6       (_csrFile_io_mmu_context_pmpaddr_6),
    .io_mmu_context_pmpaddr_7       (_csrFile_io_mmu_context_pmpaddr_7),
    .io_mmu_context_permissionEvent (io_l1d_csr_permissionEvent),
    .io_wfiWakeup                   (_csrFile_io_wfiWakeup),
    .io_interruptPending            (_csrFile_io_interruptPending),
    .io_interruptCause              (_csrFile_io_interruptCause),
    .io_csr_illegal                 (_csrFile_io_csr_illegal)
  );
  Scoreboard scoreboard (
    .clock                  (clock),
    .reset                  (reset),
    .io_set_valid
      (wbCommit
       & (_scoreboard_io_pipe_2_valid_T | wb_fp | wb_load & wbResponse
          & io_l1d_resp_bits_kind == 2'h1) & wb_writes),
    .io_set_bits_rd_isFp    (wb_rd_isFp),
    .io_set_bits_rd_idx     (wb_rd_idx),
    .io_set_bits_source
      (wb_mem ? 2'h0 : wb_div ? 2'h1 : _scoreboard_io_pipe_2_bits_source_T),
    .io_clear_valid         (_writeback_io_clear_valid),
    .io_clear_bits_isFp     (_writeback_io_clear_bits_isFp),
    .io_clear_bits_idx      (_writeback_io_clear_bits_idx),
    .io_pipe_0_valid        (exMul | exDiv | exFpLong | exMem),
    .io_pipe_0_bits_rd_isFp (exBank),
    .io_pipe_0_bits_rd_idx  (exWrites ? ex_rd_addr : 5'h0),
    .io_pipe_0_bits_source  (exMem ? 2'h0 : exDiv ? 2'h1 : {1'h1, ~exMul}),
    .io_pipe_1_valid        (mem_valid & (mem_mul | mem_div | mem_fp | mem_mem)),
    .io_pipe_1_bits_rd_isFp (mem_rd_isFp),
    .io_pipe_1_bits_rd_idx  (mem_writes ? mem_rd_idx : 5'h0),
    .io_pipe_1_bits_source  (mem_mem ? 2'h0 : mem_div ? 2'h1 : {1'h1, ~mem_mul}),
    .io_pipe_2_valid        (wb_valid & (_scoreboard_io_pipe_2_valid_T | wb_fp | wb_mem)),
    .io_pipe_2_bits_rd_isFp (wb_rd_isFp),
    .io_pipe_2_bits_rd_idx  (wb_writes ? wb_rd_idx : 5'h0),
    .io_pipe_2_bits_source
      (wb_mem ? 2'h0 : wb_div ? 2'h1 : _scoreboard_io_pipe_2_bits_source_T),
    .io_operands_0_used     (scoreboard_io_operands_0_used),
    .io_operands_0_rd_isFp  (_fpDecoder_io_ctrl_usesFpr1),
    .io_operands_0_rd_idx   (io_fetchBuffer_bits_inst[19:15]),
    .io_operands_1_used     (scoreboard_io_operands_1_used),
    .io_operands_1_rd_isFp  (_fpDecoder_io_ctrl_usesFpr2),
    .io_operands_1_rd_idx   (io_fetchBuffer_bits_inst[24:20]),
    .io_operands_2_used     (_fpDecoder_io_ctrl_usesFpr3),
    .io_operands_2_rd_idx   (io_fetchBuffer_bits_inst[31:27]),
    .io_operands_3_used
      (_fpDecoder_io_ctrl_valid
         ? _fpDecoder_io_ctrl_writesFpr | _fpDecoder_io_ctrl_writesGpr
         : _decoder_io_exe_ctrl_wb_en),
    .io_operands_3_rd_isFp  (_fpDecoder_io_ctrl_valid & _fpDecoder_io_ctrl_writesFpr),
    .io_operands_3_rd_idx   (io_fetchBuffer_bits_inst[11:7]),
    .io_idValid             (io_fetchBuffer_valid),
    .io_idLeave             (idLeave),
    .io_csr                 (|_decoder_io_exe_ctrl_csr_cmd),
    .io_fpFlagsPending      (_fpUnit_io_committedFlagsOnly),
    .io_gprBusy             (_scoreboard_io_gprBusy),
    .io_fprBusy             (_scoreboard_io_fprBusy),
    .io_hazard              (_scoreboard_io_hazard),
    .io_sourceStall_0       (_scoreboard_io_sourceStall_0),
    .io_sourceStall_1       (_scoreboard_io_sourceStall_1),
    .io_sourceStall_2       (_scoreboard_io_sourceStall_2)
  );
  Writeback writeback (
    .clock                    (clock),
    .reset                    (reset),
    .io_late_ready            (io_l1d_late_ready),
    .io_late_valid            (io_l1d_late_valid),
    .io_late_bits_rd_isFp     (io_l1d_late_bits_rd_isFp),
    .io_late_bits_rd_idx      (io_l1d_late_bits_rd_idx),
    .io_late_bits_data        (io_l1d_late_bits_data),
    .io_late_bits_error       (io_l1d_late_bits_error),
    .io_div_ready             (_writeback_io_div_ready),
    .io_div_valid             (_divUnit_io_result_valid),
    .io_div_bits_rd           (_divUnit_io_result_bits_rd),
    .io_div_bits_data         (_divUnit_io_result_bits_data),
    .io_mul_ready             (_writeback_io_mul_ready),
    .io_mul_valid             (_mulUnit_io_result_valid),
    .io_mul_bits_rd           (_mulUnit_io_result_bits_rd),
    .io_mul_bits_data         (_mulUnit_io_result_bits_data),
    .io_fp_ready              (_writeback_io_fp_ready),
    .io_fp_valid              (_fpUnit_io_result_valid),
    .io_fp_bits_rd_isFp       (_fpUnit_io_result_bits_rd_isFp),
    .io_fp_bits_rd_idx        (_fpUnit_io_result_bits_rd_idx),
    .io_fp_bits_data          (_fpUnit_io_result_bits_data),
    .io_fp_bits_flags         (_fpUnit_io_result_bits_flags),
    .io_ordinary_valid
      (wbCommit & wb_writes & ~wb_mul & ~wb_div & ~wb_fp
       & (~wb_mem | wbResponse & io_l1d_resp_bits_kind == 2'h0)),
    .io_ordinary_bits_rd_isFp (wb_rd_isFp),
    .io_ordinary_bits_rd_idx  (wb_rd_idx),
    .io_ordinary_bits_data    (wb_mem ? io_l1d_resp_bits_data : wb_data),
    .io_w2_valid              (_writeback_io_w2_valid),
    .io_w2_bits_rd_isFp       (_writeback_io_w2_bits_rd_isFp),
    .io_w2_bits_rd_idx        (_writeback_io_w2_bits_rd_idx),
    .io_w2_bits_data          (_writeback_io_w2_bits_data),
    .io_gprWrite_valid        (_writeback_io_gprWrite_valid),
    .io_gprWrite_bits_idx     (_writeback_io_gprWrite_bits_idx),
    .io_gprWrite_bits_data    (_writeback_io_gprWrite_bits_data),
    .io_fprWrite_valid        (_writeback_io_fprWrite_valid),
    .io_fprWrite_bits_idx     (_writeback_io_fprWrite_bits_idx),
    .io_fprWrite_bits_data    (_writeback_io_fprWrite_bits_data),
    .io_clear_valid           (_writeback_io_clear_valid),
    .io_clear_bits_isFp       (_writeback_io_clear_bits_isFp),
    .io_clear_bits_idx        (_writeback_io_clear_bits_idx),
    .io_fpFlags_valid         (_writeback_io_fpFlags_valid),
    .io_fpFlags_bits          (_writeback_io_fpFlags_bits),
    .io_conflict              (_writeback_io_conflict),
    .io_idStarve              (_writeback_io_idStarve),
    .io_hartFatal             (_writeback_io_hartFatal)
  );
  MulUnit mulUnit (
    .clock               (clock),
    .reset               (reset),
    .io_req_ready        (_mulUnit_io_req_ready),
    .io_req_valid        (mulUnit_io_req_valid),
    .io_req_bits_a
      (_GEN_3 ? {{33{exR1[31]}}, exR1[31:0]} : {_GEN_2 & exR1[63], exR1}),
    .io_req_bits_b
      (_GEN_3
         ? {{33{exR2[31]}}, exR2[31:0]}
         : {_GEN_2 & ex_ctrl_mul_op != 3'h2 & exR2[63], exR2}),
    .io_req_bits_op      (ex_ctrl_mul_op),
    .io_req_bits_rd      (ex_rd_addr),
    .io_commit           (wbCommit & wb_mul),
    .io_killUncommitted  (fpUnit_io_killUncommitted),
    .io_result_ready     (_writeback_io_mul_ready),
    .io_result_valid     (_mulUnit_io_result_valid),
    .io_result_bits_rd   (_mulUnit_io_result_bits_rd),
    .io_result_bits_data (_mulUnit_io_result_bits_data)
  );
  DivUnit divUnit (
    .clock                    (clock),
    .reset                    (reset),
    .io_req_ready             (_divUnit_io_req_ready),
    .io_req_valid             (divUnit_io_req_valid),
    .io_req_bits_dividendMag  (negA ? 64'h0 - dividend : dividend),
    .io_req_bits_divisorMag   (negB ? 64'h0 - divisor : divisor),
    .io_req_bits_quotientNeg  (negA ^ negB),
    .io_req_bits_remainderNeg (negA),
    .io_req_bits_isRemainder  (ex_ctrl_div_op[1]),
    .io_req_bits_isWord       (ex_ctrl_div_op[2]),
    .io_req_bits_fastValid
      (byZero | ~(ex_ctrl_div_op[0])
       & dividend == (ex_ctrl_div_op[2] ? 64'hFFFFFFFF80000000 : 64'h8000000000000000)
       & (&divisor)),
    .io_req_bits_fastData
      (ex_ctrl_div_op[2]
         ? {{32{fast[31]}}, fast}
         : byZero
             ? (ex_ctrl_div_op[1] ? exR1 : 64'hFFFFFFFFFFFFFFFF)
             : ex_ctrl_div_op[1] ? 64'h0 : exR1),
    .io_req_bits_rd           (ex_rd_addr),
    .io_commit                (wbCommit & wb_div),
    .io_killUncommitted       (fpUnit_io_killUncommitted),
    .io_result_ready          (_writeback_io_div_ready),
    .io_result_valid          (_divUnit_io_result_valid),
    .io_result_bits_rd        (_divUnit_io_result_bits_rd),
    .io_result_bits_data      (_divUnit_io_result_bits_data)
  );
  FpUnit fpUnit (
    .clock                  (clock),
    .reset                  (reset),
    .io_req_ready           (_fpUnit_io_req_ready),
    .io_req_valid           (fpUnit_io_req_valid),
    .io_req_bits_operandA   (_fpUnit_io_req_bits_operandC_T ? 64'h0 : fp1),
    .io_req_bits_operandB   (_fpUnit_io_req_bits_operandC_T ? fp1 : exFprRead_1),
    .io_req_bits_operandC
      (_fpUnit_io_req_bits_operandC_T
         ? exFprRead_1
         : exFprRead_fromMem_2
             ? mem_data
             : exFprRead_fromWb_2
                 ? wb_data
                 : exFprRead_fromW2_2 ? _writeback_io_w2_bits_data : exFpr_2),
    .io_req_bits_rm
      (exFp_usesArchitecturalRm & (&exFp_rm) ? _csrFile_io_frm : exFp_rm),
    .io_req_bits_operation  (exFp_operation),
    .io_req_bits_opMod      (exFp_opMod),
    .io_req_bits_srcFmt     (exFp_srcFmt),
    .io_req_bits_dstFmt     (exFp_dstFmt),
    .io_req_bits_intFmt     (exFp_intFmt),
    .io_req_bits_rd_isFp    (exBank),
    .io_req_bits_rd_idx     (ex_rd_addr),
    .io_commit              (wbCommit & wb_fp),
    .io_killUncommitted     (fpUnit_io_killUncommitted),
    .io_result_ready        (_writeback_io_fp_ready),
    .io_result_valid        (_fpUnit_io_result_valid),
    .io_result_bits_rd_isFp (_fpUnit_io_result_bits_rd_isFp),
    .io_result_bits_rd_idx  (_fpUnit_io_result_bits_rd_idx),
    .io_result_bits_data    (_fpUnit_io_result_bits_data),
    .io_result_bits_flags   (_fpUnit_io_result_bits_flags),
    .io_committedFlagsOnly  (_fpUnit_io_committedFlagsOnly)
  );
  ALU alu (
    .io_alu_op  (ex_ctrl_alu_op),
    .io_alu_in1 (_GEN[ex_ctrl_sel_alu1]),
    .io_alu_in2 (_GEN_1[ex_ctrl_sel_alu2]),
    .io_is_w    (ex_ctrl_is_w),
    .io_alu_out (_alu_io_alu_out)
  );
  BRU bru (
    .io_bru_op      (ex_ctrl_bru_op),
    .io_rs1_data    (exR1),
    .io_rs2_data    (exR2),
    .io_take_branch (_bru_io_take_branch)
  );
  JAU jau (
    .io_sel_jpc_i (ex_ctrl_sel_jpc_i),
    .io_sel_jpc_o (ex_ctrl_sel_jpc_o),
    .io_pc        (ex_pc),
    .io_rs1_data  (exR1),
    .io_imm       (ex_imm),
    .io_jmp_addr  (_jau_io_jmp_addr)
  );
  assign io_fetchBuffer_ready = io_fetchBuffer_ready_0;
  assign io_l1d_req_valid = io_l1d_req_valid_0;
  assign io_l1d_req_bits_op =
    ex_inst[6:0] == 7'hF
      ? 3'h5
      : exFp_isStore
          ? 3'h1
          : ex_ctrl_mem_op == 3'h4
              ? 3'h4
              : {1'h0,
                 ex_ctrl_mem_op == 3'h3
                   ? 2'h3
                   : ex_ctrl_mem_op == 3'h2 ? 2'h2 : {1'h0, ex_ctrl_mem_op == 3'h1}};
  assign io_l1d_req_bits_vaddr = _address_T_3;
  assign io_l1d_req_bits_size = exFp_valid ? {1'h1, exFp_isDouble} : ex_inst[13:12];
  assign io_l1d_req_bits_signed = ~(ex_inst[14]);
  assign io_l1d_req_bits_amoFunc = ex_ctrl_amo_func;
  assign io_l1d_req_bits_aq = ex_ctrl_amo_aq;
  assign io_l1d_req_bits_rl = ex_ctrl_amo_rl;
  assign io_l1d_req_bits_wdata = io_l1d_req_bits_wdata_0;
  assign io_l1d_req_bits_rd_isFp = exBank;
  assign io_l1d_req_bits_rd_idx = ex_rd_addr;
  assign io_l1d_req_bits_isFlw = exFp_isLoad & ~exFp_isDouble;
  assign io_l1d_s1Kill = fpUnit_io_killUncommitted;
  assign io_l1d_s2Kill = fpUnit_io_killUncommitted;
  assign io_l1d_trapClearRsv = csrFile_io_trap_valid;
  assign io_l1d_csr_privilege = _csrFile_io_mmu_context_privilege;
  assign io_l1d_csr_mprv = _csrFile_io_mmu_context_mprv;
  assign io_l1d_csr_mpp = _csrFile_io_mmu_context_mpp;
  assign io_l1d_csr_pmpcfg_0 = _csrFile_io_mmu_context_pmpcfg_0;
  assign io_l1d_csr_pmpcfg_1 = _csrFile_io_mmu_context_pmpcfg_1;
  assign io_l1d_csr_pmpcfg_2 = _csrFile_io_mmu_context_pmpcfg_2;
  assign io_l1d_csr_pmpcfg_3 = _csrFile_io_mmu_context_pmpcfg_3;
  assign io_l1d_csr_pmpcfg_4 = _csrFile_io_mmu_context_pmpcfg_4;
  assign io_l1d_csr_pmpcfg_5 = _csrFile_io_mmu_context_pmpcfg_5;
  assign io_l1d_csr_pmpcfg_6 = _csrFile_io_mmu_context_pmpcfg_6;
  assign io_l1d_csr_pmpcfg_7 = _csrFile_io_mmu_context_pmpcfg_7;
  assign io_l1d_csr_pmpaddr_0 = _csrFile_io_mmu_context_pmpaddr_0;
  assign io_l1d_csr_pmpaddr_1 = _csrFile_io_mmu_context_pmpaddr_1;
  assign io_l1d_csr_pmpaddr_2 = _csrFile_io_mmu_context_pmpaddr_2;
  assign io_l1d_csr_pmpaddr_3 = _csrFile_io_mmu_context_pmpaddr_3;
  assign io_l1d_csr_pmpaddr_4 = _csrFile_io_mmu_context_pmpaddr_4;
  assign io_l1d_csr_pmpaddr_5 = _csrFile_io_mmu_context_pmpaddr_5;
  assign io_l1d_csr_pmpaddr_6 = _csrFile_io_mmu_context_pmpaddr_6;
  assign io_l1d_csr_pmpaddr_7 = _csrFile_io_mmu_context_pmpaddr_7;
  assign io_translationBlocked = io_translationBlocked_0;
  assign io_frontendBtbUpdate_valid = io_frontendBtbUpdate_valid_0;
  assign io_frontendBtbUpdate_pc = btb_pc;
  assign io_frontendBtbUpdate_target = btb_target;
  assign io_frontendBtbUpdate_predType = btb_predType;
  assign io_frontendPhtUpdate_valid = io_frontendGhrUpdate_valid_0;
  assign io_frontendPhtUpdate_idx = ex_pred_phtIdx;
  assign io_frontendPhtUpdate_taken = taken;
  assign io_frontendGhrUpdate_valid = io_frontendGhrUpdate_valid_0;
  assign io_frontendGhrUpdate_taken = taken;
  assign io_frontendRedirect_valid = io_frontendRedirect_valid_0;
  assign io_frontendRedirect_flush =
    io_frontendRedirect_valid_0 | io_translationBlocked_0
    & ~io_frontendRedirect_flush_REG;
  assign io_frontendRedirect_cacheFlush = wbCommit & wb_fencei;
  assign io_frontendRedirect_target = io_frontendRedirect_target_0;
  assign io_mmuContext_privilege = _csrFile_io_mmu_context_privilege;
  assign io_mmuContext_mprv = _csrFile_io_mmu_context_mprv;
  assign io_mmuContext_mpp = _csrFile_io_mmu_context_mpp;
  assign io_mmuContext_pmpcfg_0 = _csrFile_io_mmu_context_pmpcfg_0;
  assign io_mmuContext_pmpcfg_1 = _csrFile_io_mmu_context_pmpcfg_1;
  assign io_mmuContext_pmpcfg_2 = _csrFile_io_mmu_context_pmpcfg_2;
  assign io_mmuContext_pmpcfg_3 = _csrFile_io_mmu_context_pmpcfg_3;
  assign io_mmuContext_pmpcfg_4 = _csrFile_io_mmu_context_pmpcfg_4;
  assign io_mmuContext_pmpcfg_5 = _csrFile_io_mmu_context_pmpcfg_5;
  assign io_mmuContext_pmpcfg_6 = _csrFile_io_mmu_context_pmpcfg_6;
  assign io_mmuContext_pmpcfg_7 = _csrFile_io_mmu_context_pmpcfg_7;
  assign io_mmuContext_pmpaddr_0 = _csrFile_io_mmu_context_pmpaddr_0;
  assign io_mmuContext_pmpaddr_1 = _csrFile_io_mmu_context_pmpaddr_1;
  assign io_mmuContext_pmpaddr_2 = _csrFile_io_mmu_context_pmpaddr_2;
  assign io_mmuContext_pmpaddr_3 = _csrFile_io_mmu_context_pmpaddr_3;
  assign io_mmuContext_pmpaddr_4 = _csrFile_io_mmu_context_pmpaddr_4;
  assign io_mmuContext_pmpaddr_5 = _csrFile_io_mmu_context_pmpaddr_5;
  assign io_mmuContext_pmpaddr_6 = _csrFile_io_mmu_context_pmpaddr_6;
  assign io_mmuContext_pmpaddr_7 = _csrFile_io_mmu_context_pmpaddr_7;
  assign io_sfence_valid = io_sfence_valid_0;
  assign io_sfence_vaddr = wb_address;
  assign io_sfence_asid = wb_storeData[15:0];
  assign io_sfence_useVaddr = |wb_rs1;
  assign io_sfence_useAsid = |wb_rs2;
  assign io_hartFatal = _writeback_io_hartFatal;
  assign io_estop = stopped | _io_estop_T;
endmodule

