// Generated by CIRCT firtool-1.128.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Scoreboard(
  input         clock,
                reset,
                io_set_valid,
                io_set_bits_rd_isFp,
  input  [4:0]  io_set_bits_rd_idx,
  input  [1:0]  io_set_bits_source,
  input         io_clear_valid,
                io_clear_bits_isFp,
  input  [4:0]  io_clear_bits_idx,
  input         io_pipe_0_valid,
                io_pipe_0_bits_rd_isFp,
  input  [4:0]  io_pipe_0_bits_rd_idx,
  input  [1:0]  io_pipe_0_bits_source,
  input         io_pipe_1_valid,
                io_pipe_1_bits_rd_isFp,
  input  [4:0]  io_pipe_1_bits_rd_idx,
  input  [1:0]  io_pipe_1_bits_source,
  input         io_pipe_2_valid,
                io_pipe_2_bits_rd_isFp,
  input  [4:0]  io_pipe_2_bits_rd_idx,
  input  [1:0]  io_pipe_2_bits_source,
  input         io_operands_0_used,
                io_operands_0_rd_isFp,
  input  [4:0]  io_operands_0_rd_idx,
  input         io_operands_1_used,
                io_operands_1_rd_isFp,
  input  [4:0]  io_operands_1_rd_idx,
  input         io_operands_2_used,
  input  [4:0]  io_operands_2_rd_idx,
  input         io_operands_3_used,
                io_operands_3_rd_isFp,
  input  [4:0]  io_operands_3_rd_idx,
  input         io_idValid,
                io_idLeave,
                io_csr,
                io_fpFlagsPending,
  output [31:0] io_gprBusy,
                io_fprBusy,
  output        io_hazard,
                io_sourceStall_0,
                io_sourceStall_1,
                io_sourceStall_2
);

  reg  [31:0]      gprBusy;
  reg  [31:0]      fprBusy;
  reg  [1:0]       gprSource_0;
  reg  [1:0]       gprSource_1;
  reg  [1:0]       gprSource_2;
  reg  [1:0]       gprSource_3;
  reg  [1:0]       gprSource_4;
  reg  [1:0]       gprSource_5;
  reg  [1:0]       gprSource_6;
  reg  [1:0]       gprSource_7;
  reg  [1:0]       gprSource_8;
  reg  [1:0]       gprSource_9;
  reg  [1:0]       gprSource_10;
  reg  [1:0]       gprSource_11;
  reg  [1:0]       gprSource_12;
  reg  [1:0]       gprSource_13;
  reg  [1:0]       gprSource_14;
  reg  [1:0]       gprSource_15;
  reg  [1:0]       gprSource_16;
  reg  [1:0]       gprSource_17;
  reg  [1:0]       gprSource_18;
  reg  [1:0]       gprSource_19;
  reg  [1:0]       gprSource_20;
  reg  [1:0]       gprSource_21;
  reg  [1:0]       gprSource_22;
  reg  [1:0]       gprSource_23;
  reg  [1:0]       gprSource_24;
  reg  [1:0]       gprSource_25;
  reg  [1:0]       gprSource_26;
  reg  [1:0]       gprSource_27;
  reg  [1:0]       gprSource_28;
  reg  [1:0]       gprSource_29;
  reg  [1:0]       gprSource_30;
  reg  [1:0]       gprSource_31;
  reg  [1:0]       fprSource_0;
  reg  [1:0]       fprSource_1;
  reg  [1:0]       fprSource_2;
  reg  [1:0]       fprSource_3;
  reg  [1:0]       fprSource_4;
  reg  [1:0]       fprSource_5;
  reg  [1:0]       fprSource_6;
  reg  [1:0]       fprSource_7;
  reg  [1:0]       fprSource_8;
  reg  [1:0]       fprSource_9;
  reg  [1:0]       fprSource_10;
  reg  [1:0]       fprSource_11;
  reg  [1:0]       fprSource_12;
  reg  [1:0]       fprSource_13;
  reg  [1:0]       fprSource_14;
  reg  [1:0]       fprSource_15;
  reg  [1:0]       fprSource_16;
  reg  [1:0]       fprSource_17;
  reg  [1:0]       fprSource_18;
  reg  [1:0]       fprSource_19;
  reg  [1:0]       fprSource_20;
  reg  [1:0]       fprSource_21;
  reg  [1:0]       fprSource_22;
  reg  [1:0]       fprSource_23;
  reg  [1:0]       fprSource_24;
  reg  [1:0]       fprSource_25;
  reg  [1:0]       fprSource_26;
  reg  [1:0]       fprSource_27;
  reg  [1:0]       fprSource_28;
  reg  [1:0]       fprSource_29;
  reg  [1:0]       fprSource_30;
  reg  [1:0]       fprSource_31;
  wire [5:0]       _GEN = {io_set_bits_rd_isFp, io_set_bits_rd_idx};
  wire [31:0]      _GEN_0 = {27'h0, io_set_bits_rd_idx};
  wire [31:0]      gSet =
    io_set_valid & (|_GEN) & ~io_set_bits_rd_isFp ? 32'h1 << _GEN_0 : 32'h0;
  wire [31:0]      fSet =
    io_set_valid & (|_GEN) & io_set_bits_rd_isFp ? 32'h1 << _GEN_0 : 32'h0;
  wire [5:0]       _GEN_1 = {io_clear_bits_isFp, io_clear_bits_idx};
  wire [31:0]      _GEN_2 = {27'h0, io_clear_bits_idx};
  wire [31:0]      gClear =
    io_clear_valid & (|_GEN_1) & ~io_clear_bits_isFp ? 32'h1 << _GEN_2 : 32'h0;
  wire [31:0]      fClear =
    io_clear_valid & (|_GEN_1) & io_clear_bits_isFp ? 32'h1 << _GEN_2 : 32'h0;
  wire [31:0]      gEffective = gprBusy & ~gClear;
  wire [31:0]      fEffective = fprBusy & ~fClear;
  wire [31:0]      _GEN_3 = {27'h0, io_operands_0_rd_idx};
  wire [31:0]      _matches_sb_T_96 = fEffective >> _GEN_3;
  wire [31:0][1:0] _GEN_4 =
    {{fprSource_31},
     {fprSource_30},
     {fprSource_29},
     {fprSource_28},
     {fprSource_27},
     {fprSource_26},
     {fprSource_25},
     {fprSource_24},
     {fprSource_23},
     {fprSource_22},
     {fprSource_21},
     {fprSource_20},
     {fprSource_19},
     {fprSource_18},
     {fprSource_17},
     {fprSource_16},
     {fprSource_15},
     {fprSource_14},
     {fprSource_13},
     {fprSource_12},
     {fprSource_11},
     {fprSource_10},
     {fprSource_9},
     {fprSource_8},
     {fprSource_7},
     {fprSource_6},
     {fprSource_5},
     {fprSource_4},
     {fprSource_3},
     {fprSource_2},
     {fprSource_1},
     {fprSource_0}};
  wire [31:0]      _matches_sb_T_100 = gEffective >> _GEN_3;
  wire [31:0][1:0] _GEN_5 =
    {{gprSource_31},
     {gprSource_30},
     {gprSource_29},
     {gprSource_28},
     {gprSource_27},
     {gprSource_26},
     {gprSource_25},
     {gprSource_24},
     {gprSource_23},
     {gprSource_22},
     {gprSource_21},
     {gprSource_20},
     {gprSource_19},
     {gprSource_18},
     {gprSource_17},
     {gprSource_16},
     {gprSource_15},
     {gprSource_14},
     {gprSource_13},
     {gprSource_12},
     {gprSource_11},
     {gprSource_10},
     {gprSource_9},
     {gprSource_8},
     {gprSource_7},
     {gprSource_6},
     {gprSource_5},
     {gprSource_4},
     {gprSource_3},
     {gprSource_2},
     {gprSource_1},
     {gprSource_0}};
  wire [5:0]       _GEN_6 = {io_pipe_0_bits_rd_isFp, io_pipe_0_bits_rd_idx};
  wire             _csrSources_T_255 = io_pipe_0_bits_source == 2'h0;
  wire [5:0]       _matches_pipe_T_425 = {io_pipe_0_bits_rd_isFp, io_pipe_0_bits_rd_idx};
  wire [5:0]       _matches_pipe_T_360 = {io_operands_0_rd_isFp, io_operands_0_rd_idx};
  wire [5:0]       _GEN_7 = {io_pipe_1_bits_rd_isFp, io_pipe_1_bits_rd_idx};
  wire             _csrSources_T_257 = io_pipe_1_bits_source == 2'h0;
  wire [5:0]       _matches_pipe_T_434 = {io_pipe_1_bits_rd_isFp, io_pipe_1_bits_rd_idx};
  wire [5:0]       _GEN_8 = {io_pipe_2_bits_rd_isFp, io_pipe_2_bits_rd_idx};
  wire             _csrSources_T_259 = io_pipe_2_bits_source == 2'h0;
  wire [5:0]       _matches_pipe_T_443 = {io_pipe_2_bits_rd_isFp, io_pipe_2_bits_rd_idx};
  wire [5:0]       _GEN_9 = {io_operands_0_rd_isFp, io_operands_0_rd_idx};
  wire [31:0]      _GEN_10 = {27'h0, io_operands_1_rd_idx};
  wire [31:0]      _matches_sb_T_104 = fEffective >> _GEN_10;
  wire [31:0]      _matches_sb_T_108 = gEffective >> _GEN_10;
  wire [5:0]       _matches_pipe_T_388 = {io_operands_1_rd_isFp, io_operands_1_rd_idx};
  wire [5:0]       _GEN_11 = {io_operands_1_rd_isFp, io_operands_1_rd_idx};
  wire [31:0]      _matches_sb_T_112 = fEffective >> io_operands_2_rd_idx;
  wire [5:0]       _matches_pipe_T_416 = {1'h1, io_operands_2_rd_idx};
  wire [31:0]      _GEN_12 = {27'h0, io_operands_3_rd_idx};
  wire [31:0]      _matches_sb_T_120 = fEffective >> _GEN_12;
  wire [31:0]      _matches_sb_T_124 = gEffective >> _GEN_12;
  wire [5:0]       _matches_pipe_T_444 = {io_operands_3_rd_isFp, io_operands_3_rd_idx};
  wire [5:0]       _GEN_13 = {io_operands_3_rd_isFp, io_operands_3_rd_idx};
  wire             matches_0 =
    io_operands_0_used & (|_GEN_9)
    & ((io_operands_0_rd_isFp
          ? _matches_sb_T_96[0] & _GEN_4[io_operands_0_rd_idx] == 2'h0
          : _matches_sb_T_100[0] & _GEN_5[io_operands_0_rd_idx] == 2'h0) | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_255 & _matches_pipe_T_425 == _matches_pipe_T_360
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_257
       & _matches_pipe_T_434 == _matches_pipe_T_360 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_259 & _matches_pipe_T_443 == _matches_pipe_T_360)
    | io_operands_1_used & (|_GEN_11)
    & ((io_operands_1_rd_isFp
          ? _matches_sb_T_104[0] & _GEN_4[io_operands_1_rd_idx] == 2'h0
          : _matches_sb_T_108[0] & _GEN_5[io_operands_1_rd_idx] == 2'h0) | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_255 & _matches_pipe_T_425 == _matches_pipe_T_388
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_257
       & _matches_pipe_T_434 == _matches_pipe_T_388 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_259 & _matches_pipe_T_443 == _matches_pipe_T_388)
    | io_operands_2_used
    & (_matches_sb_T_112[0] & _GEN_4[io_operands_2_rd_idx] == 2'h0 | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_255 & _matches_pipe_T_425 == _matches_pipe_T_416
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_257
       & _matches_pipe_T_434 == _matches_pipe_T_416 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_259 & _matches_pipe_T_443 == _matches_pipe_T_416)
    | io_operands_3_used & (|_GEN_13)
    & ((io_operands_3_rd_isFp
          ? _matches_sb_T_120[0] & _GEN_4[io_operands_3_rd_idx] == 2'h0
          : _matches_sb_T_124[0] & _GEN_5[io_operands_3_rd_idx] == 2'h0) | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_255 & _matches_pipe_T_425 == _matches_pipe_T_444
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_257
       & _matches_pipe_T_434 == _matches_pipe_T_444 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_259 & _matches_pipe_T_443 == _matches_pipe_T_444);
  wire             _csrSources_T_518 = io_pipe_0_bits_source == 2'h1;
  wire             _csrSources_T_520 = io_pipe_1_bits_source == 2'h1;
  wire             _csrSources_T_522 = io_pipe_2_bits_source == 2'h1;
  wire             matches_1 =
    io_operands_0_used & (|_GEN_9)
    & ((io_operands_0_rd_isFp
          ? _matches_sb_T_96[0] & _GEN_4[io_operands_0_rd_idx] == 2'h1
          : _matches_sb_T_100[0] & _GEN_5[io_operands_0_rd_idx] == 2'h1) | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_518 & _matches_pipe_T_425 == _matches_pipe_T_360
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_520
       & _matches_pipe_T_434 == _matches_pipe_T_360 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_522 & _matches_pipe_T_443 == _matches_pipe_T_360)
    | io_operands_1_used & (|_GEN_11)
    & ((io_operands_1_rd_isFp
          ? _matches_sb_T_104[0] & _GEN_4[io_operands_1_rd_idx] == 2'h1
          : _matches_sb_T_108[0] & _GEN_5[io_operands_1_rd_idx] == 2'h1) | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_518 & _matches_pipe_T_425 == _matches_pipe_T_388
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_520
       & _matches_pipe_T_434 == _matches_pipe_T_388 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_522 & _matches_pipe_T_443 == _matches_pipe_T_388)
    | io_operands_2_used
    & (_matches_sb_T_112[0] & _GEN_4[io_operands_2_rd_idx] == 2'h1 | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_518 & _matches_pipe_T_425 == _matches_pipe_T_416
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_520
       & _matches_pipe_T_434 == _matches_pipe_T_416 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_522 & _matches_pipe_T_443 == _matches_pipe_T_416)
    | io_operands_3_used & (|_GEN_13)
    & ((io_operands_3_rd_isFp
          ? _matches_sb_T_120[0] & _GEN_4[io_operands_3_rd_idx] == 2'h1
          : _matches_sb_T_124[0] & _GEN_5[io_operands_3_rd_idx] == 2'h1) | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_518 & _matches_pipe_T_425 == _matches_pipe_T_444
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_520
       & _matches_pipe_T_434 == _matches_pipe_T_444 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_522 & _matches_pipe_T_443 == _matches_pipe_T_444);
  wire             _csrSources_T_781 = io_pipe_0_bits_source == 2'h2;
  wire             _csrSources_T_783 = io_pipe_1_bits_source == 2'h2;
  wire             _csrSources_T_785 = io_pipe_2_bits_source == 2'h2;
  wire             matches_2 =
    io_operands_0_used & (|_GEN_9)
    & ((io_operands_0_rd_isFp
          ? _matches_sb_T_96[0] & _GEN_4[io_operands_0_rd_idx] == 2'h2
          : _matches_sb_T_100[0] & _GEN_5[io_operands_0_rd_idx] == 2'h2) | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_781 & _matches_pipe_T_425 == _matches_pipe_T_360
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_783
       & _matches_pipe_T_434 == _matches_pipe_T_360 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_785 & _matches_pipe_T_443 == _matches_pipe_T_360)
    | io_operands_1_used & (|_GEN_11)
    & ((io_operands_1_rd_isFp
          ? _matches_sb_T_104[0] & _GEN_4[io_operands_1_rd_idx] == 2'h2
          : _matches_sb_T_108[0] & _GEN_5[io_operands_1_rd_idx] == 2'h2) | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_781 & _matches_pipe_T_425 == _matches_pipe_T_388
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_783
       & _matches_pipe_T_434 == _matches_pipe_T_388 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_785 & _matches_pipe_T_443 == _matches_pipe_T_388)
    | io_operands_2_used
    & (_matches_sb_T_112[0] & _GEN_4[io_operands_2_rd_idx] == 2'h2 | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_781 & _matches_pipe_T_425 == _matches_pipe_T_416
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_783
       & _matches_pipe_T_434 == _matches_pipe_T_416 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_785 & _matches_pipe_T_443 == _matches_pipe_T_416)
    | io_operands_3_used & (|_GEN_13)
    & ((io_operands_3_rd_isFp
          ? _matches_sb_T_120[0] & _GEN_4[io_operands_3_rd_idx] == 2'h2
          : _matches_sb_T_124[0] & _GEN_5[io_operands_3_rd_idx] == 2'h2) | io_pipe_0_valid
       & (|_GEN_6) & _csrSources_T_781 & _matches_pipe_T_425 == _matches_pipe_T_444
       | io_pipe_1_valid & (|_GEN_7) & _csrSources_T_783
       & _matches_pipe_T_434 == _matches_pipe_T_444 | io_pipe_2_valid & (|_GEN_8)
       & _csrSources_T_785 & _matches_pipe_T_443 == _matches_pipe_T_444);
  wire             io_hazard_0 =
    matches_0 | matches_1 | matches_2 | io_operands_0_used & (|_GEN_9)
    & ((io_operands_0_rd_isFp
          ? _matches_sb_T_96[0] & (&_GEN_4[io_operands_0_rd_idx])
          : _matches_sb_T_100[0] & (&_GEN_5[io_operands_0_rd_idx])) | io_pipe_0_valid
       & (|_GEN_6) & (&io_pipe_0_bits_source) & _matches_pipe_T_425 == _matches_pipe_T_360
       | io_pipe_1_valid & (|_GEN_7) & (&io_pipe_1_bits_source)
       & _matches_pipe_T_434 == _matches_pipe_T_360 | io_pipe_2_valid & (|_GEN_8)
       & (&io_pipe_2_bits_source) & _matches_pipe_T_443 == _matches_pipe_T_360)
    | io_operands_1_used & (|_GEN_11)
    & ((io_operands_1_rd_isFp
          ? _matches_sb_T_104[0] & (&_GEN_4[io_operands_1_rd_idx])
          : _matches_sb_T_108[0] & (&_GEN_5[io_operands_1_rd_idx])) | io_pipe_0_valid
       & (|_GEN_6) & (&io_pipe_0_bits_source) & _matches_pipe_T_425 == _matches_pipe_T_388
       | io_pipe_1_valid & (|_GEN_7) & (&io_pipe_1_bits_source)
       & _matches_pipe_T_434 == _matches_pipe_T_388 | io_pipe_2_valid & (|_GEN_8)
       & (&io_pipe_2_bits_source) & _matches_pipe_T_443 == _matches_pipe_T_388)
    | io_operands_2_used
    & (_matches_sb_T_112[0] & (&_GEN_4[io_operands_2_rd_idx]) | io_pipe_0_valid
       & (|_GEN_6) & (&io_pipe_0_bits_source) & _matches_pipe_T_425 == _matches_pipe_T_416
       | io_pipe_1_valid & (|_GEN_7) & (&io_pipe_1_bits_source)
       & _matches_pipe_T_434 == _matches_pipe_T_416 | io_pipe_2_valid & (|_GEN_8)
       & (&io_pipe_2_bits_source) & _matches_pipe_T_443 == _matches_pipe_T_416)
    | io_operands_3_used & (|_GEN_13)
    & ((io_operands_3_rd_isFp
          ? _matches_sb_T_120[0] & (&_GEN_4[io_operands_3_rd_idx])
          : _matches_sb_T_124[0] & (&_GEN_5[io_operands_3_rd_idx])) | io_pipe_0_valid
       & (|_GEN_6) & (&io_pipe_0_bits_source) & _matches_pipe_T_425 == _matches_pipe_T_444
       | io_pipe_1_valid & (|_GEN_7) & (&io_pipe_1_bits_source)
       & _matches_pipe_T_434 == _matches_pipe_T_444 | io_pipe_2_valid & (|_GEN_8)
       & (&io_pipe_2_bits_source) & _matches_pipe_T_443 == _matches_pipe_T_444) | io_csr
    & ((|{gprBusy, fprBusy}) | io_fpFlagsPending | io_pipe_0_valid | io_pipe_1_valid
       | io_pipe_2_valid);
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (~reset & gprBusy[0]) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S01] x0 busy\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~((gSet & gClear) == 32'h0 & (fSet & fClear) == 32'h0)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S10] same rd set and clear\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~((gSet & gprBusy) == 32'h0 & (fSet & fprBusy) == 32'h0)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S01] duplicate outstanding rd\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~((gClear & ~gprBusy) == 32'h0 & (fClear & ~fprBusy) == 32'h0)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S08] completion without committed pending destination\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~io_idLeave | ~io_hazard_0)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S03/S14] ID left with dependency or CSR drain hazard\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    automatic logic _GEN_14 = io_set_valid & (|_GEN);
    automatic logic _GEN_15 = io_set_bits_rd_idx == 5'h0;
    automatic logic _GEN_16 = io_set_bits_rd_idx == 5'h1;
    automatic logic _GEN_17 = io_set_bits_rd_idx == 5'h2;
    automatic logic _GEN_18 = io_set_bits_rd_idx == 5'h3;
    automatic logic _GEN_19 = io_set_bits_rd_idx == 5'h4;
    automatic logic _GEN_20 = io_set_bits_rd_idx == 5'h5;
    automatic logic _GEN_21 = io_set_bits_rd_idx == 5'h6;
    automatic logic _GEN_22 = io_set_bits_rd_idx == 5'h7;
    automatic logic _GEN_23 = io_set_bits_rd_idx == 5'h8;
    automatic logic _GEN_24 = io_set_bits_rd_idx == 5'h9;
    automatic logic _GEN_25 = io_set_bits_rd_idx == 5'hA;
    automatic logic _GEN_26 = io_set_bits_rd_idx == 5'hB;
    automatic logic _GEN_27 = io_set_bits_rd_idx == 5'hC;
    automatic logic _GEN_28 = io_set_bits_rd_idx == 5'hD;
    automatic logic _GEN_29 = io_set_bits_rd_idx == 5'hE;
    automatic logic _GEN_30 = io_set_bits_rd_idx == 5'hF;
    automatic logic _GEN_31 = io_set_bits_rd_idx == 5'h10;
    automatic logic _GEN_32 = io_set_bits_rd_idx == 5'h11;
    automatic logic _GEN_33 = io_set_bits_rd_idx == 5'h12;
    automatic logic _GEN_34 = io_set_bits_rd_idx == 5'h13;
    automatic logic _GEN_35 = io_set_bits_rd_idx == 5'h14;
    automatic logic _GEN_36 = io_set_bits_rd_idx == 5'h15;
    automatic logic _GEN_37 = io_set_bits_rd_idx == 5'h16;
    automatic logic _GEN_38 = io_set_bits_rd_idx == 5'h17;
    automatic logic _GEN_39 = io_set_bits_rd_idx == 5'h18;
    automatic logic _GEN_40 = io_set_bits_rd_idx == 5'h19;
    automatic logic _GEN_41 = io_set_bits_rd_idx == 5'h1A;
    automatic logic _GEN_42 = io_set_bits_rd_idx == 5'h1B;
    automatic logic _GEN_43 = io_set_bits_rd_idx == 5'h1C;
    automatic logic _GEN_44 = io_set_bits_rd_idx == 5'h1D;
    automatic logic _GEN_45 = io_set_bits_rd_idx == 5'h1E;
    if (reset) begin
      gprBusy <= 32'h0;
      fprBusy <= 32'h0;
    end
    else begin
      gprBusy <= gprBusy & ~gClear | gSet;
      fprBusy <= fprBusy & ~fClear | fSet;
    end
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_15) begin
    end
    else
      gprSource_0 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_16) begin
    end
    else
      gprSource_1 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_17) begin
    end
    else
      gprSource_2 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_18) begin
    end
    else
      gprSource_3 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_19) begin
    end
    else
      gprSource_4 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_20) begin
    end
    else
      gprSource_5 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_21) begin
    end
    else
      gprSource_6 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_22) begin
    end
    else
      gprSource_7 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_23) begin
    end
    else
      gprSource_8 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_24) begin
    end
    else
      gprSource_9 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_25) begin
    end
    else
      gprSource_10 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_26) begin
    end
    else
      gprSource_11 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_27) begin
    end
    else
      gprSource_12 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_28) begin
    end
    else
      gprSource_13 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_29) begin
    end
    else
      gprSource_14 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_30) begin
    end
    else
      gprSource_15 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_31) begin
    end
    else
      gprSource_16 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_32) begin
    end
    else
      gprSource_17 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_33) begin
    end
    else
      gprSource_18 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_34) begin
    end
    else
      gprSource_19 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_35) begin
    end
    else
      gprSource_20 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_36) begin
    end
    else
      gprSource_21 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_37) begin
    end
    else
      gprSource_22 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_38) begin
    end
    else
      gprSource_23 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_39) begin
    end
    else
      gprSource_24 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_40) begin
    end
    else
      gprSource_25 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_41) begin
    end
    else
      gprSource_26 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_42) begin
    end
    else
      gprSource_27 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_43) begin
    end
    else
      gprSource_28 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_44) begin
    end
    else
      gprSource_29 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~_GEN_45) begin
    end
    else
      gprSource_30 <= io_set_bits_source;
    if (~_GEN_14 | io_set_bits_rd_isFp | ~(&io_set_bits_rd_idx)) begin
    end
    else
      gprSource_31 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_15)
      fprSource_0 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_16)
      fprSource_1 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_17)
      fprSource_2 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_18)
      fprSource_3 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_19)
      fprSource_4 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_20)
      fprSource_5 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_21)
      fprSource_6 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_22)
      fprSource_7 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_23)
      fprSource_8 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_24)
      fprSource_9 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_25)
      fprSource_10 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_26)
      fprSource_11 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_27)
      fprSource_12 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_28)
      fprSource_13 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_29)
      fprSource_14 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_30)
      fprSource_15 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_31)
      fprSource_16 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_32)
      fprSource_17 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_33)
      fprSource_18 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_34)
      fprSource_19 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_35)
      fprSource_20 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_36)
      fprSource_21 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_37)
      fprSource_22 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_38)
      fprSource_23 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_39)
      fprSource_24 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_40)
      fprSource_25 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_41)
      fprSource_26 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_42)
      fprSource_27 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_43)
      fprSource_28 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_44)
      fprSource_29 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & _GEN_45)
      fprSource_30 <= io_set_bits_source;
    if (_GEN_14 & io_set_bits_rd_isFp & (&io_set_bits_rd_idx))
      fprSource_31 <= io_set_bits_source;
  end // always @(posedge)
  assign io_gprBusy = gprBusy;
  assign io_fprBusy = fprBusy;
  assign io_hazard = io_hazard_0;
  assign io_sourceStall_0 =
    io_idValid & ~io_idLeave
    & (matches_0 | io_csr
       & (gprBusy[0] & gprSource_0 == 2'h0 | fprBusy[0] & fprSource_0 == 2'h0 | gprBusy[1]
          & gprSource_1 == 2'h0 | fprBusy[1] & fprSource_1 == 2'h0 | gprBusy[2]
          & gprSource_2 == 2'h0 | fprBusy[2] & fprSource_2 == 2'h0 | gprBusy[3]
          & gprSource_3 == 2'h0 | fprBusy[3] & fprSource_3 == 2'h0 | gprBusy[4]
          & gprSource_4 == 2'h0 | fprBusy[4] & fprSource_4 == 2'h0 | gprBusy[5]
          & gprSource_5 == 2'h0 | fprBusy[5] & fprSource_5 == 2'h0 | gprBusy[6]
          & gprSource_6 == 2'h0 | fprBusy[6] & fprSource_6 == 2'h0 | gprBusy[7]
          & gprSource_7 == 2'h0 | fprBusy[7] & fprSource_7 == 2'h0 | gprBusy[8]
          & gprSource_8 == 2'h0 | fprBusy[8] & fprSource_8 == 2'h0 | gprBusy[9]
          & gprSource_9 == 2'h0 | fprBusy[9] & fprSource_9 == 2'h0 | gprBusy[10]
          & gprSource_10 == 2'h0 | fprBusy[10] & fprSource_10 == 2'h0 | gprBusy[11]
          & gprSource_11 == 2'h0 | fprBusy[11] & fprSource_11 == 2'h0 | gprBusy[12]
          & gprSource_12 == 2'h0 | fprBusy[12] & fprSource_12 == 2'h0 | gprBusy[13]
          & gprSource_13 == 2'h0 | fprBusy[13] & fprSource_13 == 2'h0 | gprBusy[14]
          & gprSource_14 == 2'h0 | fprBusy[14] & fprSource_14 == 2'h0 | gprBusy[15]
          & gprSource_15 == 2'h0 | fprBusy[15] & fprSource_15 == 2'h0 | gprBusy[16]
          & gprSource_16 == 2'h0 | fprBusy[16] & fprSource_16 == 2'h0 | gprBusy[17]
          & gprSource_17 == 2'h0 | fprBusy[17] & fprSource_17 == 2'h0 | gprBusy[18]
          & gprSource_18 == 2'h0 | fprBusy[18] & fprSource_18 == 2'h0 | gprBusy[19]
          & gprSource_19 == 2'h0 | fprBusy[19] & fprSource_19 == 2'h0 | gprBusy[20]
          & gprSource_20 == 2'h0 | fprBusy[20] & fprSource_20 == 2'h0 | gprBusy[21]
          & gprSource_21 == 2'h0 | fprBusy[21] & fprSource_21 == 2'h0 | gprBusy[22]
          & gprSource_22 == 2'h0 | fprBusy[22] & fprSource_22 == 2'h0 | gprBusy[23]
          & gprSource_23 == 2'h0 | fprBusy[23] & fprSource_23 == 2'h0 | gprBusy[24]
          & gprSource_24 == 2'h0 | fprBusy[24] & fprSource_24 == 2'h0 | gprBusy[25]
          & gprSource_25 == 2'h0 | fprBusy[25] & fprSource_25 == 2'h0 | gprBusy[26]
          & gprSource_26 == 2'h0 | fprBusy[26] & fprSource_26 == 2'h0 | gprBusy[27]
          & gprSource_27 == 2'h0 | fprBusy[27] & fprSource_27 == 2'h0 | gprBusy[28]
          & gprSource_28 == 2'h0 | fprBusy[28] & fprSource_28 == 2'h0 | gprBusy[29]
          & gprSource_29 == 2'h0 | fprBusy[29] & fprSource_29 == 2'h0 | gprBusy[30]
          & gprSource_30 == 2'h0 | fprBusy[30] & fprSource_30 == 2'h0 | gprBusy[31]
          & gprSource_31 == 2'h0 | fprBusy[31] & fprSource_31 == 2'h0 | io_pipe_0_valid
          & _csrSources_T_255 | io_pipe_1_valid & _csrSources_T_257 | io_pipe_2_valid
          & _csrSources_T_259));
  assign io_sourceStall_1 =
    io_idValid & ~io_idLeave
    & (matches_1 | io_csr
       & (gprBusy[0] & gprSource_0 == 2'h1 | fprBusy[0] & fprSource_0 == 2'h1 | gprBusy[1]
          & gprSource_1 == 2'h1 | fprBusy[1] & fprSource_1 == 2'h1 | gprBusy[2]
          & gprSource_2 == 2'h1 | fprBusy[2] & fprSource_2 == 2'h1 | gprBusy[3]
          & gprSource_3 == 2'h1 | fprBusy[3] & fprSource_3 == 2'h1 | gprBusy[4]
          & gprSource_4 == 2'h1 | fprBusy[4] & fprSource_4 == 2'h1 | gprBusy[5]
          & gprSource_5 == 2'h1 | fprBusy[5] & fprSource_5 == 2'h1 | gprBusy[6]
          & gprSource_6 == 2'h1 | fprBusy[6] & fprSource_6 == 2'h1 | gprBusy[7]
          & gprSource_7 == 2'h1 | fprBusy[7] & fprSource_7 == 2'h1 | gprBusy[8]
          & gprSource_8 == 2'h1 | fprBusy[8] & fprSource_8 == 2'h1 | gprBusy[9]
          & gprSource_9 == 2'h1 | fprBusy[9] & fprSource_9 == 2'h1 | gprBusy[10]
          & gprSource_10 == 2'h1 | fprBusy[10] & fprSource_10 == 2'h1 | gprBusy[11]
          & gprSource_11 == 2'h1 | fprBusy[11] & fprSource_11 == 2'h1 | gprBusy[12]
          & gprSource_12 == 2'h1 | fprBusy[12] & fprSource_12 == 2'h1 | gprBusy[13]
          & gprSource_13 == 2'h1 | fprBusy[13] & fprSource_13 == 2'h1 | gprBusy[14]
          & gprSource_14 == 2'h1 | fprBusy[14] & fprSource_14 == 2'h1 | gprBusy[15]
          & gprSource_15 == 2'h1 | fprBusy[15] & fprSource_15 == 2'h1 | gprBusy[16]
          & gprSource_16 == 2'h1 | fprBusy[16] & fprSource_16 == 2'h1 | gprBusy[17]
          & gprSource_17 == 2'h1 | fprBusy[17] & fprSource_17 == 2'h1 | gprBusy[18]
          & gprSource_18 == 2'h1 | fprBusy[18] & fprSource_18 == 2'h1 | gprBusy[19]
          & gprSource_19 == 2'h1 | fprBusy[19] & fprSource_19 == 2'h1 | gprBusy[20]
          & gprSource_20 == 2'h1 | fprBusy[20] & fprSource_20 == 2'h1 | gprBusy[21]
          & gprSource_21 == 2'h1 | fprBusy[21] & fprSource_21 == 2'h1 | gprBusy[22]
          & gprSource_22 == 2'h1 | fprBusy[22] & fprSource_22 == 2'h1 | gprBusy[23]
          & gprSource_23 == 2'h1 | fprBusy[23] & fprSource_23 == 2'h1 | gprBusy[24]
          & gprSource_24 == 2'h1 | fprBusy[24] & fprSource_24 == 2'h1 | gprBusy[25]
          & gprSource_25 == 2'h1 | fprBusy[25] & fprSource_25 == 2'h1 | gprBusy[26]
          & gprSource_26 == 2'h1 | fprBusy[26] & fprSource_26 == 2'h1 | gprBusy[27]
          & gprSource_27 == 2'h1 | fprBusy[27] & fprSource_27 == 2'h1 | gprBusy[28]
          & gprSource_28 == 2'h1 | fprBusy[28] & fprSource_28 == 2'h1 | gprBusy[29]
          & gprSource_29 == 2'h1 | fprBusy[29] & fprSource_29 == 2'h1 | gprBusy[30]
          & gprSource_30 == 2'h1 | fprBusy[30] & fprSource_30 == 2'h1 | gprBusy[31]
          & gprSource_31 == 2'h1 | fprBusy[31] & fprSource_31 == 2'h1 | io_pipe_0_valid
          & _csrSources_T_518 | io_pipe_1_valid & _csrSources_T_520 | io_pipe_2_valid
          & _csrSources_T_522));
  assign io_sourceStall_2 =
    io_idValid & ~io_idLeave
    & (matches_2 | io_csr
       & (gprBusy[0] & gprSource_0 == 2'h2 | fprBusy[0] & fprSource_0 == 2'h2 | gprBusy[1]
          & gprSource_1 == 2'h2 | fprBusy[1] & fprSource_1 == 2'h2 | gprBusy[2]
          & gprSource_2 == 2'h2 | fprBusy[2] & fprSource_2 == 2'h2 | gprBusy[3]
          & gprSource_3 == 2'h2 | fprBusy[3] & fprSource_3 == 2'h2 | gprBusy[4]
          & gprSource_4 == 2'h2 | fprBusy[4] & fprSource_4 == 2'h2 | gprBusy[5]
          & gprSource_5 == 2'h2 | fprBusy[5] & fprSource_5 == 2'h2 | gprBusy[6]
          & gprSource_6 == 2'h2 | fprBusy[6] & fprSource_6 == 2'h2 | gprBusy[7]
          & gprSource_7 == 2'h2 | fprBusy[7] & fprSource_7 == 2'h2 | gprBusy[8]
          & gprSource_8 == 2'h2 | fprBusy[8] & fprSource_8 == 2'h2 | gprBusy[9]
          & gprSource_9 == 2'h2 | fprBusy[9] & fprSource_9 == 2'h2 | gprBusy[10]
          & gprSource_10 == 2'h2 | fprBusy[10] & fprSource_10 == 2'h2 | gprBusy[11]
          & gprSource_11 == 2'h2 | fprBusy[11] & fprSource_11 == 2'h2 | gprBusy[12]
          & gprSource_12 == 2'h2 | fprBusy[12] & fprSource_12 == 2'h2 | gprBusy[13]
          & gprSource_13 == 2'h2 | fprBusy[13] & fprSource_13 == 2'h2 | gprBusy[14]
          & gprSource_14 == 2'h2 | fprBusy[14] & fprSource_14 == 2'h2 | gprBusy[15]
          & gprSource_15 == 2'h2 | fprBusy[15] & fprSource_15 == 2'h2 | gprBusy[16]
          & gprSource_16 == 2'h2 | fprBusy[16] & fprSource_16 == 2'h2 | gprBusy[17]
          & gprSource_17 == 2'h2 | fprBusy[17] & fprSource_17 == 2'h2 | gprBusy[18]
          & gprSource_18 == 2'h2 | fprBusy[18] & fprSource_18 == 2'h2 | gprBusy[19]
          & gprSource_19 == 2'h2 | fprBusy[19] & fprSource_19 == 2'h2 | gprBusy[20]
          & gprSource_20 == 2'h2 | fprBusy[20] & fprSource_20 == 2'h2 | gprBusy[21]
          & gprSource_21 == 2'h2 | fprBusy[21] & fprSource_21 == 2'h2 | gprBusy[22]
          & gprSource_22 == 2'h2 | fprBusy[22] & fprSource_22 == 2'h2 | gprBusy[23]
          & gprSource_23 == 2'h2 | fprBusy[23] & fprSource_23 == 2'h2 | gprBusy[24]
          & gprSource_24 == 2'h2 | fprBusy[24] & fprSource_24 == 2'h2 | gprBusy[25]
          & gprSource_25 == 2'h2 | fprBusy[25] & fprSource_25 == 2'h2 | gprBusy[26]
          & gprSource_26 == 2'h2 | fprBusy[26] & fprSource_26 == 2'h2 | gprBusy[27]
          & gprSource_27 == 2'h2 | fprBusy[27] & fprSource_27 == 2'h2 | gprBusy[28]
          & gprSource_28 == 2'h2 | fprBusy[28] & fprSource_28 == 2'h2 | gprBusy[29]
          & gprSource_29 == 2'h2 | fprBusy[29] & fprSource_29 == 2'h2 | gprBusy[30]
          & gprSource_30 == 2'h2 | fprBusy[30] & fprSource_30 == 2'h2 | gprBusy[31]
          & gprSource_31 == 2'h2 | fprBusy[31] & fprSource_31 == 2'h2 | io_pipe_0_valid
          & _csrSources_T_781 | io_pipe_1_valid & _csrSources_T_783 | io_pipe_2_valid
          & _csrSources_T_785));
endmodule

