// Generated by CIRCT firtool-1.128.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Writeback(
  input         clock,
                reset,
  output        io_late_ready,
  input         io_late_valid,
                io_late_bits_rd_isFp,
  input  [4:0]  io_late_bits_rd_idx,
  input  [63:0] io_late_bits_data,
  input         io_late_bits_error,
  output        io_div_ready,
  input         io_div_valid,
  input  [4:0]  io_div_bits_rd,
  input  [63:0] io_div_bits_data,
  output        io_mul_ready,
  input         io_mul_valid,
  input  [4:0]  io_mul_bits_rd,
  input  [63:0] io_mul_bits_data,
  output        io_fp_ready,
  input         io_fp_valid,
                io_fp_bits_rd_isFp,
  input  [4:0]  io_fp_bits_rd_idx,
  input  [63:0] io_fp_bits_data,
  input  [4:0]  io_fp_bits_flags,
  input         io_ordinary_valid,
                io_ordinary_bits_rd_isFp,
  input  [4:0]  io_ordinary_bits_rd_idx,
  input  [63:0] io_ordinary_bits_data,
  output        io_w2_valid,
                io_w2_bits_rd_isFp,
  output [4:0]  io_w2_bits_rd_idx,
  output [63:0] io_w2_bits_data,
  output        io_gprWrite_valid,
  output [4:0]  io_gprWrite_bits_idx,
  output [63:0] io_gprWrite_bits_data,
  output        io_fprWrite_valid,
  output [4:0]  io_fprWrite_bits_idx,
  output [63:0] io_fprWrite_bits_data,
  output        io_clear_valid,
                io_clear_bits_isFp,
  output [4:0]  io_clear_bits_idx,
  output        io_fpFlags_valid,
  output [4:0]  io_fpFlags_bits,
  output [1:0]  io_conflict,
  output        io_idStarve,
                io_hartFatal
);

  reg         w2_valid;
  reg         w2_bits_rd_isFp;
  reg  [4:0]  w2_bits_rd_idx;
  reg  [63:0] w2_bits_data;
  reg         lateReg_valid;
  reg         lateReg_bits_rd_isFp;
  reg  [4:0]  lateReg_bits_rd_idx;
  reg  [63:0] lateReg_bits_data;
  reg         lateReg_bits_error;
  wire [3:0]  selected =
    lateReg_valid
    & ~(~lateReg_bits_error & (|{lateReg_bits_rd_isFp, lateReg_bits_rd_idx}) & w2_valid
        & lateReg_bits_rd_isFp == w2_bits_rd_isFp)
      ? 4'h1
      : io_div_valid & ~((|io_div_bits_rd) & w2_valid & ~w2_bits_rd_isFp)
          ? 4'h2
          : io_mul_valid & ~((|io_mul_bits_rd) & w2_valid & ~w2_bits_rd_isFp)
              ? 4'h4
              : {io_fp_valid
                   & ~((|{io_fp_bits_rd_isFp, io_fp_bits_rd_idx}) & w2_valid
                       & io_fp_bits_rd_isFp == w2_bits_rd_isFp),
                 3'h0};
  wire        io_late_ready_0 = ~lateReg_valid | selected[0];
  reg  [1:0]  starvation_0;
  reg  [1:0]  starvation_1;
  reg         inFlight_0;
  reg         inFlight_1;
  wire        granted =
    selected[0] & ~lateReg_bits_rd_isFp | selected[1] | selected[2] | selected[3]
    & ~io_fp_bits_rd_isFp;
  wire        conflicts_0 =
    (lateReg_valid & ~lateReg_bits_rd_isFp | io_div_valid | io_mul_valid | io_fp_valid
     & ~io_fp_bits_rd_isFp) & ~granted;
  wire        protect_0 = (&starvation_0) & ~inFlight_0;
  wire        granted_1 =
    selected[0] & lateReg_bits_rd_isFp | selected[3] & io_fp_bits_rd_isFp;
  wire        conflicts_1 =
    (lateReg_valid & lateReg_bits_rd_isFp | io_fp_valid & io_fp_bits_rd_isFp)
    & ~granted_1;
  wire        protect_1 = (&starvation_1) & ~inFlight_1;
  wire        rd_isFp =
    selected[0] & lateReg_bits_rd_isFp | selected[3] & io_fp_bits_rd_isFp;
  wire [4:0]  rd_idx =
    (selected[0] ? lateReg_bits_rd_idx : 5'h0) | (selected[1] ? io_div_bits_rd : 5'h0)
    | (selected[2] ? io_mul_bits_rd : 5'h0) | (selected[3] ? io_fp_bits_rd_idx : 5'h0);
  wire [63:0] data =
    (selected[0] ? lateReg_bits_data : 64'h0) | (selected[1] ? io_div_bits_data : 64'h0)
    | (selected[2] ? io_mul_bits_data : 64'h0) | (selected[3] ? io_fp_bits_data : 64'h0);
  wire        error = lateReg_valid & lateReg_bits_error;
  reg         fatal;
  wire [5:0]  _GEN = {rd_isFp, rd_idx};
  wire        bgWrite = (|selected) & ~(selected[0] & lateReg_bits_error) & (|_GEN);
  wire        background = bgWrite & ~rd_isFp;
  wire        io_gprWrite_valid_0 = background | w2_valid & ~w2_bits_rd_isFp;
  wire [4:0]  io_gprWrite_bits_idx_0 = background ? rd_idx : w2_bits_rd_idx;
  wire        background_1 = bgWrite & rd_isFp;
  wire        io_fprWrite_valid_0 = background_1 | w2_valid & w2_bits_rd_isFp;
  wire        io_clear_valid_0 = (|selected) & (|_GEN);
  reg         pastActive;
  reg         wasLateBlocked;
  reg  [70:0] heldLate;
  reg         wasLateRegBlocked;
  reg  [70:0] heldLateReg;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      automatic logic       _GEN_0 = pastActive & ~reset;
      automatic logic       _GEN_1 = w2_bits_rd_isFp ? background_1 : background;
      automatic logic [2:0] _GEN_2 =
        {1'h0, {1'h0, selected[0]} + {1'h0, selected[1]}}
        + {1'h0, {1'h0, selected[2]} + {1'h0, selected[3]}};
      if (_GEN_0 & wasLateBlocked
          & ~(io_late_valid
              & {io_late_bits_rd_isFp,
                 io_late_bits_rd_idx,
                 io_late_bits_data,
                 io_late_bits_error} == heldLate)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S07] stalled late result changed\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (_GEN_0 & wasLateRegBlocked
          & ~(lateReg_valid
              & {lateReg_bits_rd_isFp,
                 lateReg_bits_rd_idx,
                 lateReg_bits_data,
                 lateReg_bits_error} == heldLateReg)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S07] stalled lateReg changed\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & (|(_GEN_2[2:1]))) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S06] background grants not one-hot\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~(selected[0]) | lateReg_valid)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S08] lateReg completion without a buffered item\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & w2_valid
          & ~((w2_bits_rd_isFp ? io_fprWrite_valid_0 : io_gprWrite_valid_0)
              & (_GEN_1 ? rd_idx : w2_bits_rd_idx) == w2_bits_rd_idx
              & (_GEN_1 ? data : w2_bits_data) == w2_bits_data)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [W2] committed ordinary write did not complete\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {~io_gprWrite_valid_0, io_gprWrite_bits_idx_0} == 6'h0) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S01] physical x0 write\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & io_clear_valid_0 != ((|selected) & (|_GEN))) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [S08] clear must equal actual completion, including fatal late\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    if (reset) begin
      w2_valid <= 1'h0;
      w2_bits_rd_isFp <= 1'h0;
      w2_bits_rd_idx <= 5'h0;
      w2_bits_data <= 64'h0;
      lateReg_valid <= 1'h0;
      lateReg_bits_rd_isFp <= 1'h0;
      lateReg_bits_rd_idx <= 5'h0;
      lateReg_bits_data <= 64'h0;
      lateReg_bits_error <= 1'h0;
      starvation_0 <= 2'h0;
      starvation_1 <= 2'h0;
      inFlight_0 <= 1'h0;
      inFlight_1 <= 1'h0;
      fatal <= 1'h0;
      pastActive <= 1'h0;
      wasLateBlocked <= 1'h0;
      wasLateRegBlocked <= 1'h0;
    end
    else begin
      automatic logic _lateReg_valid_T_2 = io_late_ready_0 & io_late_valid;
      w2_valid <=
        io_ordinary_valid & (|{io_ordinary_bits_rd_isFp, io_ordinary_bits_rd_idx});
      if (io_ordinary_valid) begin
        w2_bits_rd_isFp <= io_ordinary_bits_rd_isFp;
        w2_bits_rd_idx <= io_ordinary_bits_rd_idx;
        w2_bits_data <= io_ordinary_bits_data;
      end
      lateReg_valid <= lateReg_valid & ~(selected[0]) | _lateReg_valid_T_2;
      if (_lateReg_valid_T_2) begin
        lateReg_bits_rd_isFp <= io_late_bits_rd_isFp;
        lateReg_bits_rd_idx <= io_late_bits_rd_idx;
        lateReg_bits_data <= io_late_bits_data;
        lateReg_bits_error <= io_late_bits_error;
      end
      if (conflicts_0) begin
        if (starvation_0 != 2'h3)
          starvation_0 <= starvation_0 + 2'h1;
      end
      else
        starvation_0 <= 2'h0;
      if (conflicts_1) begin
        if (starvation_1 != 2'h3)
          starvation_1 <= starvation_1 + 2'h1;
      end
      else
        starvation_1 <= 2'h0;
      inFlight_0 <= ~granted & (protect_0 | inFlight_0);
      inFlight_1 <= ~granted_1 & (protect_1 | inFlight_1);
      fatal <= error | fatal;
      pastActive <= ~reset;
      wasLateBlocked <= io_late_valid & ~io_late_ready_0;
      wasLateRegBlocked <= lateReg_valid & ~(selected[0]);
    end
    heldLate <=
      {io_late_bits_rd_isFp, io_late_bits_rd_idx, io_late_bits_data, io_late_bits_error};
    heldLateReg <=
      {lateReg_bits_rd_isFp, lateReg_bits_rd_idx, lateReg_bits_data, lateReg_bits_error};
  end // always @(posedge)
  assign io_late_ready = io_late_ready_0;
  assign io_div_ready = selected[1];
  assign io_mul_ready = selected[2];
  assign io_fp_ready = selected[3];
  assign io_w2_valid = w2_valid;
  assign io_w2_bits_rd_isFp = w2_bits_rd_isFp;
  assign io_w2_bits_rd_idx = w2_bits_rd_idx;
  assign io_w2_bits_data = w2_bits_data;
  assign io_gprWrite_valid = io_gprWrite_valid_0;
  assign io_gprWrite_bits_idx = io_gprWrite_bits_idx_0;
  assign io_gprWrite_bits_data = background ? data : w2_bits_data;
  assign io_fprWrite_valid = io_fprWrite_valid_0;
  assign io_fprWrite_bits_idx = background_1 ? rd_idx : w2_bits_rd_idx;
  assign io_fprWrite_bits_data = background_1 ? data : w2_bits_data;
  assign io_clear_valid = io_clear_valid_0;
  assign io_clear_bits_isFp = rd_isFp;
  assign io_clear_bits_idx = rd_idx;
  assign io_fpFlags_valid = selected[3];
  assign io_fpFlags_bits = io_fp_bits_flags;
  assign io_conflict = {1'h0, conflicts_0} + {1'h0, conflicts_1};
  assign io_idStarve = |{protect_1, protect_0};
  assign io_hartFatal = fatal | error;
endmodule

