#ifndef BREEZE_PLATFORM_H
#define BREEZE_PLATFORM_H

#include <stdint.h>

#define BREEZE_MTIME_ADDR          UINT64_C(0x0200bff8)
#define BREEZE_MTIMECMP_ADDR       UINT64_C(0x02004000)

#define BREEZE_UART_BASE           UINT64_C(0x12001000)
#define BREEZE_UART_RXTX_ADDR      (BREEZE_UART_BASE + UINT64_C(0x00))
#define BREEZE_UART_TXFULL_ADDR    (BREEZE_UART_BASE + UINT64_C(0x04))
#define BREEZE_UART_RXEMPTY_ADDR   (BREEZE_UART_BASE + UINT64_C(0x08))
#define BREEZE_UART_EV_STATUS_ADDR (BREEZE_UART_BASE + UINT64_C(0x0c))
#define BREEZE_UART_EV_PENDING_ADDR (BREEZE_UART_BASE + UINT64_C(0x10))
#define BREEZE_UART_EV_ENABLE_ADDR (BREEZE_UART_BASE + UINT64_C(0x14))

#define BREEZE_UART_EVENT_TX       UINT32_C(1)
#define BREEZE_UART_EVENT_RX       UINT32_C(2)

#endif
