# Autogenerated by LiteX / git: 68785e254
set -e
file_path="design/build"
sed -E "s|ROOT|${FLOW_ROOT}/${file_path}|g" xilinx_kcu105.tcl > xilinx_kcu105_tmp.tcl
vivado -mode batch -source xilinx_kcu105_tmp.tcl
